// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteApiCollectionByHash, deleteApiTrackingById, getApiAbout, getApiBangumiByIdEpisodeOffset, getApiBangumiSearchMikan, getApiBangumiSearchTmdb, getApiCalendar, getApiCollectionFilesByHash, getApiHealth, getApiLogs, getApiTorrentSearch, getApiSettings, getApiTracking, getApiTrackingBangumis, getApiTrackingById, type Options, postApiCollectionAdd, postApiCollectionConfirm, postApiDownloaderTest, postApiNotificationTest, postApiTorrentDownload, postApiTracking, postApiUpdate, putApiBangumiByIdTmdbId, putApiSettings, putApiTrackingById } from '../sdk.gen';
import type { DeleteApiCollectionByHashData, DeleteApiTrackingByIdData, GetApiAboutData, GetApiAboutResponse, GetApiBangumiByIdEpisodeOffsetData, GetApiBangumiByIdEpisodeOffsetResponse, GetApiBangumiSearchMikanData, GetApiBangumiSearchMikanResponse, GetApiBangumiSearchTmdbData, GetApiBangumiSearchTmdbResponse, GetApiCalendarData, GetApiCalendarResponse, GetApiCollectionFilesByHashData, GetApiCollectionFilesByHashResponse, GetApiHealthData, GetApiHealthResponse, GetApiLogsData, GetApiLogsResponse, GetApiTorrentSearchData, GetApiTorrentSearchResponse, GetApiSettingsData, GetApiSettingsResponse, GetApiTrackingBangumisData, GetApiTrackingBangumisResponse, GetApiTrackingByIdData, GetApiTrackingByIdResponse, GetApiTrackingData, GetApiTrackingResponse, PostApiCollectionAddData, PostApiCollectionAddResponse, PostApiCollectionConfirmData, PostApiDownloaderTestData, PostApiDownloaderTestResponse, PostApiNotificationTestData, PostApiNotificationTestResponse, PostApiTorrentDownloadData, PostApiTrackingData, PostApiTrackingResponse, PostApiUpdateData, PostApiUpdateResponse, PutApiBangumiByIdTmdbIdData, PutApiSettingsData, PutApiSettingsResponse, PutApiTrackingByIdData, PutApiTrackingByIdResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiHealthQueryKey = (options?: Options<GetApiHealthData>) => createQueryKey('getApiHealth', options);

export const getApiHealthOptions = (options?: Options<GetApiHealthData>) => queryOptions<GetApiHealthResponse, DefaultError, GetApiHealthResponse, ReturnType<typeof getApiHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiHealthQueryKey(options)
});

export const getApiAboutQueryKey = (options?: Options<GetApiAboutData>) => createQueryKey('getApiAbout', options);

export const getApiAboutOptions = (options?: Options<GetApiAboutData>) => queryOptions<GetApiAboutResponse, DefaultError, GetApiAboutResponse, ReturnType<typeof getApiAboutQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAbout({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAboutQueryKey(options)
});

export const postApiUpdateMutation = (options?: Partial<Options<PostApiUpdateData>>): UseMutationOptions<PostApiUpdateResponse, DefaultError, Options<PostApiUpdateData>> => {
    const mutationOptions: UseMutationOptions<PostApiUpdateResponse, DefaultError, Options<PostApiUpdateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiUpdate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiCalendarQueryKey = (options: Options<GetApiCalendarData>) => createQueryKey('getApiCalendar', options);

export const getApiCalendarOptions = (options: Options<GetApiCalendarData>) => queryOptions<GetApiCalendarResponse, DefaultError, GetApiCalendarResponse, ReturnType<typeof getApiCalendarQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiCalendar({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiCalendarQueryKey(options)
});

export const getApiSettingsQueryKey = (options?: Options<GetApiSettingsData>) => createQueryKey('getApiSettings', options);

export const getApiSettingsOptions = (options?: Options<GetApiSettingsData>) => queryOptions<GetApiSettingsResponse, DefaultError, GetApiSettingsResponse, ReturnType<typeof getApiSettingsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiSettings({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiSettingsQueryKey(options)
});

export const putApiSettingsMutation = (options?: Partial<Options<PutApiSettingsData>>): UseMutationOptions<PutApiSettingsResponse, DefaultError, Options<PutApiSettingsData>> => {
    const mutationOptions: UseMutationOptions<PutApiSettingsResponse, DefaultError, Options<PutApiSettingsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiSettings({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiTrackingQueryKey = (options?: Options<GetApiTrackingData>) => createQueryKey('getApiTracking', options);

export const getApiTrackingOptions = (options?: Options<GetApiTrackingData>) => queryOptions<GetApiTrackingResponse, DefaultError, GetApiTrackingResponse, ReturnType<typeof getApiTrackingQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiTracking({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiTrackingQueryKey(options)
});

export const postApiTrackingMutation = (options?: Partial<Options<PostApiTrackingData>>): UseMutationOptions<PostApiTrackingResponse, DefaultError, Options<PostApiTrackingData>> => {
    const mutationOptions: UseMutationOptions<PostApiTrackingResponse, DefaultError, Options<PostApiTrackingData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiTracking({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiTrackingBangumisQueryKey = (options?: Options<GetApiTrackingBangumisData>) => createQueryKey('getApiTrackingBangumis', options);

export const getApiTrackingBangumisOptions = (options?: Options<GetApiTrackingBangumisData>) => queryOptions<GetApiTrackingBangumisResponse, DefaultError, GetApiTrackingBangumisResponse, ReturnType<typeof getApiTrackingBangumisQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiTrackingBangumis({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiTrackingBangumisQueryKey(options)
});

export const deleteApiTrackingByIdMutation = (options?: Partial<Options<DeleteApiTrackingByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiTrackingByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiTrackingByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiTrackingById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiTrackingByIdQueryKey = (options: Options<GetApiTrackingByIdData>) => createQueryKey('getApiTrackingById', options);

export const getApiTrackingByIdOptions = (options: Options<GetApiTrackingByIdData>) => queryOptions<GetApiTrackingByIdResponse, DefaultError, GetApiTrackingByIdResponse, ReturnType<typeof getApiTrackingByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiTrackingById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiTrackingByIdQueryKey(options)
});

export const putApiTrackingByIdMutation = (options?: Partial<Options<PutApiTrackingByIdData>>): UseMutationOptions<PutApiTrackingByIdResponse, DefaultError, Options<PutApiTrackingByIdData>> => {
    const mutationOptions: UseMutationOptions<PutApiTrackingByIdResponse, DefaultError, Options<PutApiTrackingByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiTrackingById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiTorrentSearchQueryKey = (options: Options<GetApiTorrentSearchData>) => createQueryKey('getApiTorrentSearch', options);

export const getApiTorrentSearchOptions = (options: Options<GetApiTorrentSearchData>) => queryOptions<GetApiTorrentSearchResponse, DefaultError, GetApiTorrentSearchResponse, ReturnType<typeof getApiTorrentSearchQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiTorrentSearch({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiTorrentSearchQueryKey(options)
});

export const postApiTorrentDownloadMutation = (options?: Partial<Options<PostApiTorrentDownloadData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiTorrentDownloadData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiTorrentDownloadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiTorrentDownload({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiDownloaderTestMutation = (options?: Partial<Options<PostApiDownloaderTestData>>): UseMutationOptions<PostApiDownloaderTestResponse, DefaultError, Options<PostApiDownloaderTestData>> => {
    const mutationOptions: UseMutationOptions<PostApiDownloaderTestResponse, DefaultError, Options<PostApiDownloaderTestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiDownloaderTest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiNotificationTestMutation = (options?: Partial<Options<PostApiNotificationTestData>>): UseMutationOptions<PostApiNotificationTestResponse, DefaultError, Options<PostApiNotificationTestData>> => {
    const mutationOptions: UseMutationOptions<PostApiNotificationTestResponse, DefaultError, Options<PostApiNotificationTestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiNotificationTest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiBangumiSearchTmdbQueryKey = (options: Options<GetApiBangumiSearchTmdbData>) => createQueryKey('getApiBangumiSearchTmdb', options);

export const getApiBangumiSearchTmdbOptions = (options: Options<GetApiBangumiSearchTmdbData>) => queryOptions<GetApiBangumiSearchTmdbResponse, DefaultError, GetApiBangumiSearchTmdbResponse, ReturnType<typeof getApiBangumiSearchTmdbQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiBangumiSearchTmdb({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiBangumiSearchTmdbQueryKey(options)
});

export const getApiBangumiSearchMikanQueryKey = (options: Options<GetApiBangumiSearchMikanData>) => createQueryKey('getApiBangumiSearchMikan', options);

export const getApiBangumiSearchMikanOptions = (options: Options<GetApiBangumiSearchMikanData>) => queryOptions<GetApiBangumiSearchMikanResponse, DefaultError, GetApiBangumiSearchMikanResponse, ReturnType<typeof getApiBangumiSearchMikanQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiBangumiSearchMikan({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiBangumiSearchMikanQueryKey(options)
});

export const putApiBangumiByIdTmdbIdMutation = (options?: Partial<Options<PutApiBangumiByIdTmdbIdData>>): UseMutationOptions<unknown, DefaultError, Options<PutApiBangumiByIdTmdbIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutApiBangumiByIdTmdbIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiBangumiByIdTmdbId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiBangumiByIdEpisodeOffsetQueryKey = (options: Options<GetApiBangumiByIdEpisodeOffsetData>) => createQueryKey('getApiBangumiByIdEpisodeOffset', options);

export const getApiBangumiByIdEpisodeOffsetOptions = (options: Options<GetApiBangumiByIdEpisodeOffsetData>) => queryOptions<GetApiBangumiByIdEpisodeOffsetResponse, DefaultError, GetApiBangumiByIdEpisodeOffsetResponse, ReturnType<typeof getApiBangumiByIdEpisodeOffsetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiBangumiByIdEpisodeOffset({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiBangumiByIdEpisodeOffsetQueryKey(options)
});

export const getApiLogsQueryKey = (options: Options<GetApiLogsData>) => createQueryKey('getApiLogs', options);

export const getApiLogsOptions = (options: Options<GetApiLogsData>) => queryOptions<GetApiLogsResponse, DefaultError, GetApiLogsResponse, ReturnType<typeof getApiLogsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiLogs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiLogsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getApiLogsInfiniteQueryKey = (options: Options<GetApiLogsData>): QueryKey<Options<GetApiLogsData>> => createQueryKey('getApiLogs', options, true);

export const getApiLogsInfiniteOptions = (options: Options<GetApiLogsData>) => infiniteQueryOptions<GetApiLogsResponse, DefaultError, InfiniteData<GetApiLogsResponse>, QueryKey<Options<GetApiLogsData>>, number | Pick<QueryKey<Options<GetApiLogsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetApiLogsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiLogs({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiLogsInfiniteQueryKey(options)
});

export const postApiCollectionAddMutation = (options?: Partial<Options<PostApiCollectionAddData>>): UseMutationOptions<PostApiCollectionAddResponse, DefaultError, Options<PostApiCollectionAddData>> => {
    const mutationOptions: UseMutationOptions<PostApiCollectionAddResponse, DefaultError, Options<PostApiCollectionAddData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiCollectionAdd({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiCollectionFilesByHashQueryKey = (options: Options<GetApiCollectionFilesByHashData>) => createQueryKey('getApiCollectionFilesByHash', options);

export const getApiCollectionFilesByHashOptions = (options: Options<GetApiCollectionFilesByHashData>) => queryOptions<GetApiCollectionFilesByHashResponse, DefaultError, GetApiCollectionFilesByHashResponse, ReturnType<typeof getApiCollectionFilesByHashQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiCollectionFilesByHash({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiCollectionFilesByHashQueryKey(options)
});

export const postApiCollectionConfirmMutation = (options?: Partial<Options<PostApiCollectionConfirmData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiCollectionConfirmData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiCollectionConfirmData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiCollectionConfirm({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteApiCollectionByHashMutation = (options?: Partial<Options<DeleteApiCollectionByHashData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiCollectionByHashData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiCollectionByHashData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiCollectionByHash({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
