// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteApiTrackingById, getApiBangumiSearchTmdb, getApiCalendar, getApiHealth, getApiRssSearch, getApiSettings, getApiTracking, getApiTrackingBangumis, getApiTrackingById, type Options, postApiDownloaderTest, postApiMediaImport, postApiMediaLibraries, postApiMediaTest, postApiNotificationTest, postApiRssDownload, postApiTracking, putApiBangumiByIdTmdbId, putApiSettings, putApiTrackingById } from '../sdk.gen';
import type { DeleteApiTrackingByIdData, GetApiBangumiSearchTmdbData, GetApiBangumiSearchTmdbResponse, GetApiCalendarData, GetApiCalendarResponse, GetApiHealthData, GetApiHealthResponse, GetApiRssSearchData, GetApiRssSearchResponse, GetApiSettingsData, GetApiSettingsResponse, GetApiTrackingBangumisData, GetApiTrackingBangumisResponse, GetApiTrackingByIdData, GetApiTrackingByIdResponse, GetApiTrackingData, GetApiTrackingResponse, PostApiDownloaderTestData, PostApiDownloaderTestResponse, PostApiMediaImportData, PostApiMediaImportResponse, PostApiMediaLibrariesData, PostApiMediaLibrariesResponse, PostApiMediaTestData, PostApiMediaTestResponse, PostApiNotificationTestData, PostApiNotificationTestResponse, PostApiRssDownloadData, PostApiTrackingData, PostApiTrackingResponse, PutApiBangumiByIdTmdbIdData, PutApiSettingsData, PutApiSettingsResponse, PutApiTrackingByIdData, PutApiTrackingByIdResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiHealthQueryKey = (options?: Options<GetApiHealthData>) => createQueryKey('getApiHealth', options);

export const getApiHealthOptions = (options?: Options<GetApiHealthData>) => queryOptions<GetApiHealthResponse, DefaultError, GetApiHealthResponse, ReturnType<typeof getApiHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiHealthQueryKey(options)
});

export const getApiCalendarQueryKey = (options: Options<GetApiCalendarData>) => createQueryKey('getApiCalendar', options);

export const getApiCalendarOptions = (options: Options<GetApiCalendarData>) => queryOptions<GetApiCalendarResponse, DefaultError, GetApiCalendarResponse, ReturnType<typeof getApiCalendarQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiCalendar({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiCalendarQueryKey(options)
});

export const getApiSettingsQueryKey = (options?: Options<GetApiSettingsData>) => createQueryKey('getApiSettings', options);

export const getApiSettingsOptions = (options?: Options<GetApiSettingsData>) => queryOptions<GetApiSettingsResponse, DefaultError, GetApiSettingsResponse, ReturnType<typeof getApiSettingsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiSettings({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiSettingsQueryKey(options)
});

export const putApiSettingsMutation = (options?: Partial<Options<PutApiSettingsData>>): UseMutationOptions<PutApiSettingsResponse, DefaultError, Options<PutApiSettingsData>> => {
    const mutationOptions: UseMutationOptions<PutApiSettingsResponse, DefaultError, Options<PutApiSettingsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiSettings({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiTrackingQueryKey = (options?: Options<GetApiTrackingData>) => createQueryKey('getApiTracking', options);

export const getApiTrackingOptions = (options?: Options<GetApiTrackingData>) => queryOptions<GetApiTrackingResponse, DefaultError, GetApiTrackingResponse, ReturnType<typeof getApiTrackingQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiTracking({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiTrackingQueryKey(options)
});

export const postApiTrackingMutation = (options?: Partial<Options<PostApiTrackingData>>): UseMutationOptions<PostApiTrackingResponse, DefaultError, Options<PostApiTrackingData>> => {
    const mutationOptions: UseMutationOptions<PostApiTrackingResponse, DefaultError, Options<PostApiTrackingData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiTracking({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiTrackingBangumisQueryKey = (options?: Options<GetApiTrackingBangumisData>) => createQueryKey('getApiTrackingBangumis', options);

export const getApiTrackingBangumisOptions = (options?: Options<GetApiTrackingBangumisData>) => queryOptions<GetApiTrackingBangumisResponse, DefaultError, GetApiTrackingBangumisResponse, ReturnType<typeof getApiTrackingBangumisQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiTrackingBangumis({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiTrackingBangumisQueryKey(options)
});

export const deleteApiTrackingByIdMutation = (options?: Partial<Options<DeleteApiTrackingByIdData>>): UseMutationOptions<unknown, DefaultError, Options<DeleteApiTrackingByIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<DeleteApiTrackingByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteApiTrackingById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiTrackingByIdQueryKey = (options: Options<GetApiTrackingByIdData>) => createQueryKey('getApiTrackingById', options);

export const getApiTrackingByIdOptions = (options: Options<GetApiTrackingByIdData>) => queryOptions<GetApiTrackingByIdResponse, DefaultError, GetApiTrackingByIdResponse, ReturnType<typeof getApiTrackingByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiTrackingById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiTrackingByIdQueryKey(options)
});

export const putApiTrackingByIdMutation = (options?: Partial<Options<PutApiTrackingByIdData>>): UseMutationOptions<PutApiTrackingByIdResponse, DefaultError, Options<PutApiTrackingByIdData>> => {
    const mutationOptions: UseMutationOptions<PutApiTrackingByIdResponse, DefaultError, Options<PutApiTrackingByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiTrackingById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiRssSearchQueryKey = (options: Options<GetApiRssSearchData>) => createQueryKey('getApiRssSearch', options);

export const getApiRssSearchOptions = (options: Options<GetApiRssSearchData>) => queryOptions<GetApiRssSearchResponse, DefaultError, GetApiRssSearchResponse, ReturnType<typeof getApiRssSearchQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiRssSearch({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiRssSearchQueryKey(options)
});

export const postApiRssDownloadMutation = (options?: Partial<Options<PostApiRssDownloadData>>): UseMutationOptions<unknown, DefaultError, Options<PostApiRssDownloadData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PostApiRssDownloadData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiRssDownload({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiDownloaderTestMutation = (options?: Partial<Options<PostApiDownloaderTestData>>): UseMutationOptions<PostApiDownloaderTestResponse, DefaultError, Options<PostApiDownloaderTestData>> => {
    const mutationOptions: UseMutationOptions<PostApiDownloaderTestResponse, DefaultError, Options<PostApiDownloaderTestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiDownloaderTest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiNotificationTestMutation = (options?: Partial<Options<PostApiNotificationTestData>>): UseMutationOptions<PostApiNotificationTestResponse, DefaultError, Options<PostApiNotificationTestData>> => {
    const mutationOptions: UseMutationOptions<PostApiNotificationTestResponse, DefaultError, Options<PostApiNotificationTestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiNotificationTest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiMediaTestMutation = (options?: Partial<Options<PostApiMediaTestData>>): UseMutationOptions<PostApiMediaTestResponse, DefaultError, Options<PostApiMediaTestData>> => {
    const mutationOptions: UseMutationOptions<PostApiMediaTestResponse, DefaultError, Options<PostApiMediaTestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiMediaTest({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiMediaLibrariesMutation = (options?: Partial<Options<PostApiMediaLibrariesData>>): UseMutationOptions<PostApiMediaLibrariesResponse, DefaultError, Options<PostApiMediaLibrariesData>> => {
    const mutationOptions: UseMutationOptions<PostApiMediaLibrariesResponse, DefaultError, Options<PostApiMediaLibrariesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiMediaLibraries({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiMediaImportMutation = (options?: Partial<Options<PostApiMediaImportData>>): UseMutationOptions<PostApiMediaImportResponse, DefaultError, Options<PostApiMediaImportData>> => {
    const mutationOptions: UseMutationOptions<PostApiMediaImportResponse, DefaultError, Options<PostApiMediaImportData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiMediaImport({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiBangumiSearchTmdbQueryKey = (options: Options<GetApiBangumiSearchTmdbData>) => createQueryKey('getApiBangumiSearchTmdb', options);

export const getApiBangumiSearchTmdbOptions = (options: Options<GetApiBangumiSearchTmdbData>) => queryOptions<GetApiBangumiSearchTmdbResponse, DefaultError, GetApiBangumiSearchTmdbResponse, ReturnType<typeof getApiBangumiSearchTmdbQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiBangumiSearchTmdb({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiBangumiSearchTmdbQueryKey(options)
});

export const putApiBangumiByIdTmdbIdMutation = (options?: Partial<Options<PutApiBangumiByIdTmdbIdData>>): UseMutationOptions<unknown, DefaultError, Options<PutApiBangumiByIdTmdbIdData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<PutApiBangumiByIdTmdbIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiBangumiByIdTmdbId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
