// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getApiBangumiSeason, getApiCalendar, getApiHealth, getApiSettings, type Options, putApiSettings } from '../sdk.gen';
import type { GetApiBangumiSeasonData, GetApiBangumiSeasonResponse, GetApiCalendarData, GetApiCalendarResponse, GetApiHealthData, GetApiHealthResponse, GetApiSettingsData, GetApiSettingsResponse, PutApiSettingsData, PutApiSettingsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiHealthQueryKey = (options?: Options<GetApiHealthData>) => createQueryKey('getApiHealth', options);

export const getApiHealthOptions = (options?: Options<GetApiHealthData>) => queryOptions<GetApiHealthResponse, DefaultError, GetApiHealthResponse, ReturnType<typeof getApiHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiHealthQueryKey(options)
});

export const getApiBangumiSeasonQueryKey = (options: Options<GetApiBangumiSeasonData>) => createQueryKey('getApiBangumiSeason', options);

export const getApiBangumiSeasonOptions = (options: Options<GetApiBangumiSeasonData>) => queryOptions<GetApiBangumiSeasonResponse, DefaultError, GetApiBangumiSeasonResponse, ReturnType<typeof getApiBangumiSeasonQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiBangumiSeason({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiBangumiSeasonQueryKey(options)
});

export const getApiCalendarQueryKey = (options: Options<GetApiCalendarData>) => createQueryKey('getApiCalendar', options);

export const getApiCalendarOptions = (options: Options<GetApiCalendarData>) => queryOptions<GetApiCalendarResponse, DefaultError, GetApiCalendarResponse, ReturnType<typeof getApiCalendarQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiCalendar({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiCalendarQueryKey(options)
});

export const getApiSettingsQueryKey = (options?: Options<GetApiSettingsData>) => createQueryKey('getApiSettings', options);

export const getApiSettingsOptions = (options?: Options<GetApiSettingsData>) => queryOptions<GetApiSettingsResponse, DefaultError, GetApiSettingsResponse, ReturnType<typeof getApiSettingsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiSettings({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiSettingsQueryKey(options)
});

export const putApiSettingsMutation = (options?: Partial<Options<PutApiSettingsData>>): UseMutationOptions<PutApiSettingsResponse, DefaultError, Options<PutApiSettingsData>> => {
    const mutationOptions: UseMutationOptions<PutApiSettingsResponse, DefaultError, Options<PutApiSettingsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putApiSettings({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
