// This file is auto-generated by @hey-api/openapi-ts

export const BangumiSchema = {
  type: "object",
  description: "Bangumi (anime) main entity",
  required: [
    "id",
    "created_at",
    "updated_at",
    "title_chinese",
    "title_original_chinese",
    "season",
    "year",
    "total_episodes",
    "episode_offset",
    "current_episode",
    "auto_download",
    "source_type",
    "finished",
  ],
  properties: {
    air_date: {
      type: ["string", "null"],
      description: "First air date (YYYY-MM-DD format)",
    },
    air_week: {
      type: ["integer", "null"],
      format: "int32",
      description:
        "Day of week when new episodes air (0=Sunday, 1=Monday, ..., 6=Saturday)",
    },
    auto_download: {
      type: "boolean",
      description: "Auto download new episodes",
    },
    bgmtv_id: {
      type: ["integer", "null"],
      format: "int64",
      description: "Bangumi.tv ID",
    },
    created_at: {
      type: "string",
      format: "date-time",
    },
    current_episode: {
      type: "integer",
      format: "int32",
      description: "Current downloaded episode",
    },
    episode_offset: {
      type: "integer",
      format: "int32",
      description: "Episode offset",
    },
    finished: {
      type: "boolean",
      description: "Whether the bangumi has finished airing",
    },
    id: {
      type: "integer",
      format: "int64",
    },
    kind: {
      type: ["string", "null"],
      description: "Kind of bangumi (e.g., TV, Movie, OVA)",
    },
    poster_url: {
      type: ["string", "null"],
      description: "Poster URL",
    },
    save_path: {
      type: ["string", "null"],
      description: "Custom save path (None=use default)",
    },
    season: {
      type: "integer",
      format: "int32",
      description: "Season number",
    },
    source_type: {
      $ref: "#/components/schemas/SourceType",
      description: "Source type: webrip or bdrip",
    },
    title_chinese: {
      type: "string",
      description: "Chinese title (primary display)",
    },
    title_japanese: {
      type: ["string", "null"],
      description: "Japanese original name",
    },
    title_original_chinese: {
      type: "string",
      description: "Original Chinese title (native language, required, unique)",
    },
    title_original_japanese: {
      type: ["string", "null"],
      description: "Original Japanese title",
    },
    tmdb_id: {
      type: ["integer", "null"],
      format: "int64",
      description: "TMDB ID",
    },
    total_episodes: {
      type: "integer",
      format: "int32",
      description: "Total episodes (0=unknown)",
    },
    updated_at: {
      type: "string",
      format: "date-time",
    },
    year: {
      type: "integer",
      format: "int32",
      description: "Year",
    },
  },
} as const;

export const BangumiDetailSchema = {
  type: "object",
  required: ["subgroups"],
  properties: {
    subgroups: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Subgroup",
      },
    },
  },
} as const;

export const CreateBangumiSchema = {
  type: "object",
  description: "Request body for creating a new bangumi",
  required: ["title_chinese", "title_original_chinese", "year"],
  properties: {
    air_date: {
      type: ["string", "null"],
      description: "First air date (YYYY-MM-DD format)",
    },
    air_week: {
      type: ["integer", "null"],
      format: "int32",
      description:
        "Day of week when new episodes air (0=Sunday, 1=Monday, ..., 6=Saturday)",
    },
    auto_download: {
      type: "boolean",
      description: "Auto download new episodes",
    },
    bgmtv_id: {
      type: ["integer", "null"],
      format: "int64",
      description: "Bangumi.tv ID",
    },
    episode_offset: {
      type: "integer",
      format: "int32",
      description: "Episode offset",
    },
    finished: {
      type: "boolean",
      description: "Whether the bangumi has finished airing",
    },
    kind: {
      type: ["string", "null"],
      description: "Kind of bangumi (e.g., TV, Movie, OVA)",
    },
    poster_url: {
      type: ["string", "null"],
      description: "Poster URL",
    },
    rss_entries: {
      type: "array",
      items: {
        $ref: "#/components/schemas/RssEntry",
      },
      description: "RSS subscriptions to create with this bangumi",
    },
    save_path: {
      type: ["string", "null"],
      description: "Custom save path",
    },
    season: {
      type: "integer",
      format: "int32",
      description: "Season number (default: 1)",
    },
    source_type: {
      $ref: "#/components/schemas/SourceType",
      description: "Source type",
    },
    title_chinese: {
      type: "string",
      description: "Chinese title (required)",
    },
    title_japanese: {
      type: ["string", "null"],
      description: "Japanese original name",
    },
    title_original_chinese: {
      type: "string",
      description: "Original Chinese title (native language, required, unique)",
    },
    title_original_japanese: {
      type: ["string", "null"],
      description: "Original Japanese title",
    },
    tmdb_id: {
      type: ["integer", "null"],
      format: "int64",
      description: "TMDB ID",
    },
    total_episodes: {
      type: "integer",
      format: "int32",
      description: "Total episodes",
    },
    year: {
      type: "integer",
      format: "int32",
      description: "Year (required)",
    },
  },
} as const;

export const DownloaderSettingsSchema = {
  type: "object",
  description: "Downloader configuration (supports qBittorrent)",
  properties: {
    password: {
      type: "string",
      description: "Password (qBittorrent)",
    },
    type: {
      $ref: "#/components/schemas/DownloaderType",
      description: "Downloader type: qbittorrent",
    },
    url: {
      type: "string",
      description: "Downloader Web UI URL (e.g., http://localhost:8080)",
    },
    username: {
      type: "string",
      description: "Username (qBittorrent)",
    },
  },
} as const;

export const DownloaderTypeSchema = {
  type: "string",
  description: "Downloader type",
  enum: ["qbittorrent"],
} as const;

export const EpisodeSchema = {
  type: "object",
  description: "Episode item",
  required: ["id", "type", "name", "name_cn", "sort", "airdate"],
  properties: {
    airdate: {
      type: "string",
      description: "Air date",
    },
    ep: {
      type: ["number", "null"],
      format: "double",
      description: "Episode number",
    },
    id: {
      type: "integer",
      format: "int64",
    },
    name: {
      type: "string",
      description: "Original name",
    },
    name_cn: {
      type: "string",
      description: "Chinese name",
    },
    sort: {
      type: "number",
      format: "double",
      description: "Sort order",
    },
    type: {
      $ref: "#/components/schemas/EpisodeType",
      description: "Episode type: 0=本篇, 1=SP, 2=OP, 3=ED",
    },
  },
} as const;

export const EpisodeTypeSchema = {
  type: "string",
  description: "Episode type",
  enum: ["Main", "Special", "Opening", "Ending"],
} as const;

export const FilterSettingsSchema = {
  type: "object",
  description: "Filter configuration",
  properties: {
    global_rss_filters: {
      type: "array",
      items: {
        type: "string",
      },
      description: "Global RSS filters (regex patterns to exclude)",
    },
  },
} as const;

export const RssEntrySchema = {
  type: "object",
  description: "RSS entry for creating bangumi with subscriptions",
  required: ["url"],
  properties: {
    filters: {
      type: "array",
      items: {
        type: "string",
      },
      description: "Regex patterns to exclude from matching",
    },
    url: {
      type: "string",
      description: "RSS feed URL",
    },
  },
} as const;

export const SearchResultSchema = {
  type: "object",
  required: ["id", "name"],
  properties: {
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
  },
} as const;

export const SearchSubjectsResponseSchema = {
  type: "object",
  description: "Search response from POST /v0/search/subjects",
  required: ["total", "limit", "offset", "data"],
  properties: {
    data: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Subject",
      },
    },
    limit: {
      type: "integer",
      format: "int64",
    },
    offset: {
      type: "integer",
      format: "int64",
    },
    total: {
      type: "integer",
      format: "int64",
    },
  },
} as const;

export const SettingsSchema = {
  type: "object",
  description: "Application settings stored in TOML file",
  properties: {
    downloader: {
      $ref: "#/components/schemas/DownloaderSettings",
      description: "Downloader configuration",
    },
    filter: {
      $ref: "#/components/schemas/FilterSettings",
      description: "Filter configuration",
    },
  },
} as const;

export const SourceTypeSchema = {
  type: "string",
  description: "Source type for bangumi",
  enum: ["webrip", "bdrip"],
} as const;

export const SubgroupSchema = {
  type: "object",
  required: ["id", "name", "rss_url", "episodes"],
  properties: {
    episodes: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Episode",
      },
    },
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    rss_url: {
      type: "string",
    },
  },
} as const;

export const SubjectSchema = {
  type: "object",
  description: "Subject item in search results",
  required: [
    "id",
    "name",
    "name_cn",
    "date",
    "platform",
    "images",
    "image",
    "eps",
  ],
  properties: {
    date: {
      type: "string",
    },
    eps: {
      type: "integer",
      format: "int64",
    },
    id: {
      type: "integer",
      format: "int64",
    },
    image: {
      type: "string",
    },
    images: {
      $ref: "#/components/schemas/SubjectImages",
    },
    name: {
      type: "string",
    },
    name_cn: {
      type: "string",
    },
    platform: {
      type: "string",
    },
  },
} as const;

export const SubjectImagesSchema = {
  type: "object",
  description: "Subject images from BGM.tv API",
  required: ["small", "grid", "large", "medium", "common"],
  properties: {
    common: {
      type: "string",
    },
    grid: {
      type: "string",
    },
    large: {
      type: "string",
    },
    medium: {
      type: "string",
    },
    small: {
      type: "string",
    },
  },
} as const;

export const TestDownloaderRequestSchema = {
  type: "object",
  description: "Request body for testing downloader connection",
  required: ["type", "url", "username", "password"],
  properties: {
    password: {
      type: "string",
      description: "Password",
    },
    type: {
      $ref: "#/components/schemas/DownloaderType",
      description: 'Downloader type (e.g., "qbittorrent")',
    },
    url: {
      type: "string",
      description: "Downloader Web UI URL",
    },
    username: {
      type: "string",
      description: "Username",
    },
  },
} as const;

export const TvShowSchema = {
  type: "object",
  required: [
    "id",
    "name",
    "original_name",
    "overview",
    "vote_average",
    "vote_count",
    "popularity",
    "genre_ids",
    "origin_country",
    "original_language",
  ],
  properties: {
    backdrop_path: {
      type: ["string", "null"],
    },
    first_air_date: {
      type: ["string", "null"],
    },
    genre_ids: {
      type: "array",
      items: {
        type: "integer",
        format: "int64",
      },
    },
    id: {
      type: "integer",
      format: "int64",
    },
    name: {
      type: "string",
    },
    origin_country: {
      type: "array",
      items: {
        type: "string",
      },
    },
    original_language: {
      type: "string",
    },
    original_name: {
      type: "string",
    },
    overview: {
      type: "string",
    },
    popularity: {
      type: "number",
      format: "double",
    },
    poster_path: {
      type: ["string", "null"],
    },
    vote_average: {
      type: "number",
      format: "double",
    },
    vote_count: {
      type: "integer",
      format: "int64",
    },
  },
} as const;

export const UpdateDownloaderSettingsSchema = {
  type: "object",
  description: "Request body for updating downloader settings",
  properties: {
    password: {
      type: ["string", "null"],
      description: "Password (send null to clear)",
    },
    type: {
      oneOf: [
        {
          type: "null",
        },
        {
          $ref: "#/components/schemas/DownloaderType",
          description: "Downloader type: qbittorrent",
        },
      ],
    },
    url: {
      type: ["string", "null"],
      description: "Downloader Web UI URL (send null to clear)",
    },
    username: {
      type: ["string", "null"],
      description: "Username (send null to clear)",
    },
  },
} as const;

export const UpdateFilterSettingsSchema = {
  type: "object",
  description: "Request body for updating filter settings",
  properties: {
    global_rss_filters: {
      type: ["array", "null"],
      items: {
        type: "string",
      },
      description: "Global RSS filters (replaces entire array if provided)",
    },
  },
} as const;

export const UpdateSettingsSchema = {
  type: "object",
  description:
    "Request body for updating settings.\nAll fields are optional - only provided fields will be updated.",
  properties: {
    downloader: {
      oneOf: [
        {
          type: "null",
        },
        {
          $ref: "#/components/schemas/UpdateDownloaderSettings",
          description: "Downloader configuration updates",
        },
      ],
    },
    filter: {
      oneOf: [
        {
          type: "null",
        },
        {
          $ref: "#/components/schemas/UpdateFilterSettings",
          description: "Filter configuration updates",
        },
      ],
    },
  },
} as const;
