// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateBangumiData,
  CreateBangumiErrors,
  CreateBangumiResponses,
  GetBangumiData,
  GetBangumiErrors,
  GetBangumiResponses,
  GetEpisodesData,
  GetEpisodesErrors,
  GetEpisodesResponses,
  GetMikanRssData,
  GetMikanRssErrors,
  GetMikanRssResponses,
  GetSettingsData,
  GetSettingsErrors,
  GetSettingsResponses,
  ResetSettingsData,
  ResetSettingsErrors,
  ResetSettingsResponses,
  SearchBgmtvData,
  SearchBgmtvErrors,
  SearchBgmtvResponses,
  SearchMikanData,
  SearchMikanErrors,
  SearchMikanResponses,
  SearchTmdbData,
  SearchTmdbErrors,
  SearchTmdbResponses,
  UpdateSettingsData,
  UpdateSettingsErrors,
  UpdateSettingsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all bangumi
 */
export const getBangumi = <ThrowOnError extends boolean = false>(
  options?: Options<GetBangumiData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetBangumiResponses,
    GetBangumiErrors,
    ThrowOnError
  >({ url: "/api/bangumi", ...options });

/**
 * Create a new bangumi
 */
export const createBangumi = <ThrowOnError extends boolean = false>(
  options: Options<CreateBangumiData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateBangumiResponses,
    CreateBangumiErrors,
    ThrowOnError
  >({
    url: "/api/bangumi",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get episodes by subject ID from BGM.tv
 */
export const getEpisodes = <ThrowOnError extends boolean = false>(
  options: Options<GetEpisodesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetEpisodesResponses,
    GetEpisodesErrors,
    ThrowOnError
  >({ url: "/api/episodes/{subject_id}", ...options });

/**
 * Get bangumi detail with RSS URLs from Mikan
 */
export const getMikanRss = <ThrowOnError extends boolean = false>(
  options: Options<GetMikanRssData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetMikanRssResponses,
    GetMikanRssErrors,
    ThrowOnError
  >({ url: "/api/mikan/rss", ...options });

/**
 * Search for bangumi (Japanese anime) on BGM.tv
 */
export const searchBgmtv = <ThrowOnError extends boolean = false>(
  options: Options<SearchBgmtvData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchBgmtvResponses,
    SearchBgmtvErrors,
    ThrowOnError
  >({ url: "/api/search/bgmtv", ...options });

/**
 * Search for bangumi on Mikan
 */
export const searchMikan = <ThrowOnError extends boolean = false>(
  options: Options<SearchMikanData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchMikanResponses,
    SearchMikanErrors,
    ThrowOnError
  >({ url: "/api/search/mikan", ...options });

/**
 * Search for anime on TMDB using discover API
 */
export const searchTmdb = <ThrowOnError extends boolean = false>(
  options: Options<SearchTmdbData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchTmdbResponses,
    SearchTmdbErrors,
    ThrowOnError
  >({ url: "/api/search/tmdb", ...options });

/**
 * Get application settings
 */
export const getSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSettingsResponses,
    GetSettingsErrors,
    ThrowOnError
  >({ url: "/api/settings", ...options });

/**
 * Update application settings
 */
export const updateSettings = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSettingsData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateSettingsResponses,
    UpdateSettingsErrors,
    ThrowOnError
  >({
    url: "/api/settings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset settings to defaults
 */
export const resetSettings = <ThrowOnError extends boolean = false>(
  options?: Options<ResetSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    ResetSettingsResponses,
    ResetSettingsErrors,
    ThrowOnError
  >({ url: "/api/settings/reset", ...options });
