// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CleanupLogsData,
  CleanupLogsResponses,
  ClearAllLogsData,
  ClearAllLogsResponses,
  CreateBangumiData,
  CreateBangumiResponses,
  DeleteTorrentsData,
  DeleteTorrentsErrors,
  DeleteTorrentsResponses,
  FindMetadataData,
  FindMetadataResponses,
  GetBangumiByIdData,
  GetBangumiByIdErrors,
  GetBangumiByIdResponses,
  GetBangumiData,
  GetBangumiResponses,
  GetCalendarData,
  GetCalendarResponses,
  GetEpisodesData,
  GetEpisodesResponses,
  GetLogsData,
  GetLogsResponses,
  GetMetadataByIdData,
  GetMetadataByIdErrors,
  GetMetadataByIdResponses,
  GetMetadataData,
  GetMetadataDetailData,
  GetMetadataDetailResponses,
  GetMetadataResponses,
  GetMikanRssData,
  GetMikanRssResponses,
  GetSettingsData,
  GetSettingsResponses,
  ListTorrentsData,
  ListTorrentsErrors,
  ListTorrentsResponses,
  RefreshCalendarData,
  RefreshCalendarResponses,
  ResetSettingsData,
  ResetSettingsResponses,
  SearchBgmtvData,
  SearchBgmtvResponses,
  SearchMetadataData,
  SearchMetadataResponses,
  SearchMikanData,
  SearchMikanResponses,
  SearchTmdbData,
  SearchTmdbResponses,
  StreamLogsData,
  StreamLogsResponses,
  TestDownloaderConnectionData,
  TestDownloaderConnectionErrors,
  TestDownloaderConnectionResponses,
  TestNotificationData,
  TestNotificationErrors,
  TestNotificationResponses,
  TestProxyData,
  TestProxyErrors,
  TestProxyResponses,
  UpdateBangumiData,
  UpdateBangumiErrors,
  UpdateBangumiResponses,
  UpdateMetadataData,
  UpdateMetadataErrors,
  UpdateMetadataResponses,
  UpdateSettingsData,
  UpdateSettingsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get all bangumi
 */
export const getBangumi = <ThrowOnError extends boolean = false>(
  options?: Options<GetBangumiData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetBangumiResponses, unknown, ThrowOnError>({
    url: "/api/bangumi",
    ...options,
  });

/**
 * Create a new bangumi
 */
export const createBangumi = <ThrowOnError extends boolean = false>(
  options: Options<CreateBangumiData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateBangumiResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/bangumi",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a bangumi by ID with its RSS subscriptions
 */
export const getBangumiById = <ThrowOnError extends boolean = false>(
  options: Options<GetBangumiByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBangumiByIdResponses,
    GetBangumiByIdErrors,
    ThrowOnError
  >({ url: "/api/bangumi/{id}", ...options });

/**
 * Update a bangumi
 */
export const updateBangumi = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBangumiData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateBangumiResponses,
    UpdateBangumiErrors,
    ThrowOnError
  >({
    url: "/api/bangumi/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get calendar (weekly anime schedule)
 *
 * Returns cached data from database. If the database is empty for the requested season,
 * automatically fetches from Mikan/BGM.tv and populates the database.
 * Defaults to current season if year/season not specified.
 */
export const getCalendar = <ThrowOnError extends boolean = false>(
  options?: Options<GetCalendarData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetCalendarResponses, unknown, ThrowOnError>({
    url: "/api/calendar",
    ...options,
  });

/**
 * Refresh calendar data
 *
 * Re-imports calendar data from GitHub seed file.
 * Returns the updated calendar data.
 * Defaults to current season if year/season not specified.
 */
export const refreshCalendar = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshCalendarData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    RefreshCalendarResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/calendar/refresh", ...options });

/**
 * Test downloader connection with provided credentials
 */
export const testDownloaderConnection = <ThrowOnError extends boolean = false>(
  options: Options<TestDownloaderConnectionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TestDownloaderConnectionResponses,
    TestDownloaderConnectionErrors,
    ThrowOnError
  >({
    url: "/api/downloader/test",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get episodes by subject ID from BGM.tv
 */
export const getEpisodes = <ThrowOnError extends boolean = false>(
  options: Options<GetEpisodesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetEpisodesResponses, unknown, ThrowOnError>({
    url: "/api/episodes/{subject_id}",
    ...options,
  });

/**
 * Delete old logs (cleanup endpoint)
 */
export const cleanupLogs = <ThrowOnError extends boolean = false>(
  options?: Options<CleanupLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    CleanupLogsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/logs", ...options });

/**
 * Get logs with optional filtering and pagination
 */
export const getLogs = <ThrowOnError extends boolean = false>(
  options?: Options<GetLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetLogsResponses, unknown, ThrowOnError>({
    url: "/api/logs",
    ...options,
  });

/**
 * Clear all logs
 */
export const clearAllLogs = <ThrowOnError extends boolean = false>(
  options?: Options<ClearAllLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).delete<
    ClearAllLogsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/logs/all", ...options });

/**
 * Stream logs via Server-Sent Events (SSE)
 */
export const streamLogs = <ThrowOnError extends boolean = false>(
  options?: Options<StreamLogsData, ThrowOnError>,
) =>
  (options?.client ?? client).sse.get<
    StreamLogsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/logs/stream", ...options });

/**
 * Get all metadata
 */
export const getMetadata = <ThrowOnError extends boolean = false>(
  options?: Options<GetMetadataData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetMetadataResponses, unknown, ThrowOnError>({
    url: "/api/metadata",
    ...options,
  });

/**
 * Get a metadata by ID
 */
export const getMetadataById = <ThrowOnError extends boolean = false>(
  options: Options<GetMetadataByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetMetadataByIdResponses,
    GetMetadataByIdErrors,
    ThrowOnError
  >({ url: "/api/metadata/{id}", ...options });

/**
 * Update a metadata
 */
export const updateMetadata = <ThrowOnError extends boolean = false>(
  options: Options<UpdateMetadataData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateMetadataResponses,
    UpdateMetadataErrors,
    ThrowOnError
  >({
    url: "/api/metadata/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get bangumi detail with RSS URLs from Mikan
 */
export const getMikanRss = <ThrowOnError extends boolean = false>(
  options: Options<GetMikanRssData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetMikanRssResponses, unknown, ThrowOnError>({
    url: "/api/mikan/rss",
    ...options,
  });

/**
 * Test Telegram notification by sending a test message
 */
export const testNotification = <ThrowOnError extends boolean = false>(
  options: Options<TestNotificationData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TestNotificationResponses,
    TestNotificationErrors,
    ThrowOnError
  >({
    url: "/api/notification/test",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Test proxy connection by making a request to mikanani.me
 */
export const testProxy = <ThrowOnError extends boolean = false>(
  options: Options<TestProxyData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    TestProxyResponses,
    TestProxyErrors,
    ThrowOnError
  >({
    url: "/api/proxy/test",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Search for bangumi (Japanese anime) on BGM.tv
 */
export const searchBgmtv = <ThrowOnError extends boolean = false>(
  options: Options<SearchBgmtvData, ThrowOnError>,
) =>
  (options.client ?? client).get<SearchBgmtvResponses, unknown, ThrowOnError>({
    url: "/api/search/bgmtv",
    ...options,
  });

/**
 * Unified metadata search across all data sources
 *
 * Returns standardized SearchedMetadata format regardless of data source.
 */
export const searchMetadata = <ThrowOnError extends boolean = false>(
  options: Options<SearchMetadataData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    SearchMetadataResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/search/metadata", ...options });

/**
 * Get metadata detail by external ID from a specific data source
 *
 * Returns full metadata for a specific subject/show.
 */
export const getMetadataDetail = <ThrowOnError extends boolean = false>(
  options: Options<GetMetadataDetailData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetMetadataDetailResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/search/metadata/detail", ...options });

/**
 * Find best matching metadata from a specific data source
 *
 * Returns a single best matching result based on keyword and optional year filter.
 */
export const findMetadata = <ThrowOnError extends boolean = false>(
  options: Options<FindMetadataData, ThrowOnError>,
) =>
  (options.client ?? client).get<FindMetadataResponses, unknown, ThrowOnError>({
    url: "/api/search/metadata/find",
    ...options,
  });

/**
 * Search for bangumi on Mikan
 */
export const searchMikan = <ThrowOnError extends boolean = false>(
  options: Options<SearchMikanData, ThrowOnError>,
) =>
  (options.client ?? client).get<SearchMikanResponses, unknown, ThrowOnError>({
    url: "/api/search/mikan",
    ...options,
  });

/**
 * Search for anime on TMDB using discover API
 */
export const searchTmdb = <ThrowOnError extends boolean = false>(
  options: Options<SearchTmdbData, ThrowOnError>,
) =>
  (options.client ?? client).get<SearchTmdbResponses, unknown, ThrowOnError>({
    url: "/api/search/tmdb",
    ...options,
  });

/**
 * Get application settings
 */
export const getSettings = <ThrowOnError extends boolean = false>(
  options?: Options<GetSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetSettingsResponses, unknown, ThrowOnError>({
    url: "/api/settings",
    ...options,
  });

/**
 * Update application settings
 */
export const updateSettings = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSettingsData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateSettingsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/settings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset settings to defaults
 */
export const resetSettings = <ThrowOnError extends boolean = false>(
  options?: Options<ResetSettingsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    ResetSettingsResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/settings/reset", ...options });

/**
 * List all torrents
 */
export const listTorrents = <ThrowOnError extends boolean = false>(
  options?: Options<ListTorrentsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListTorrentsResponses,
    ListTorrentsErrors,
    ThrowOnError
  >({ url: "/api/torrents", ...options });

/**
 * Delete torrents
 */
export const deleteTorrents = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTorrentsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    DeleteTorrentsResponses,
    DeleteTorrentsErrors,
    ThrowOnError
  >({
    url: "/api/torrents/delete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
