// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:3000" | (string & {});
};

/**
 * Bangumi (anime) main entity
 */
export type Bangumi = {
  /**
   * First air date (YYYY-MM-DD format)
   */
  air_date?: string | null;
  /**
   * Day of week when new episodes air (0=Sunday, 1=Monday, ..., 6=Saturday)
   */
  air_week?: number | null;
  /**
   * Auto download new episodes
   */
  auto_download: boolean;
  /**
   * Bangumi.tv ID
   */
  bgmtv_id?: number | null;
  created_at: string;
  /**
   * Current downloaded episode
   */
  current_episode: number;
  /**
   * Episode offset
   */
  episode_offset: number;
  /**
   * Whether the bangumi has finished airing
   */
  finished: boolean;
  id: number;
  /**
   * Kind of bangumi (e.g., TV, Movie, OVA)
   */
  kind?: string | null;
  /**
   * Poster URL
   */
  poster_url?: string | null;
  /**
   * Custom save path (None=use default)
   */
  save_path?: string | null;
  /**
   * Season number
   */
  season: number;
  /**
   * Source type: webrip or bdrip
   */
  source_type: SourceType;
  /**
   * Chinese title (primary display)
   */
  title_chinese: string;
  /**
   * Japanese original name
   */
  title_japanese?: string | null;
  /**
   * Original Chinese title (native language, required, unique)
   */
  title_original_chinese: string;
  /**
   * Original Japanese title
   */
  title_original_japanese?: string | null;
  /**
   * TMDB ID
   */
  tmdb_id?: number | null;
  /**
   * Total episodes (0=unknown)
   */
  total_episodes: number;
  updated_at: string;
  /**
   * Year
   */
  year: number;
};

export type BangumiDetail = {
  subgroups: Array<Subgroup>;
};

/**
 * Bangumi with its RSS subscriptions
 */
export type BangumiWithRss = Bangumi & {
  /**
   * RSS subscriptions for this bangumi
   */
  rss_entries: Array<Rss>;
};

/**
 * Request to control torrents (pause/resume)
 */
export type ControlTorrentsRequest = {
  /**
   * List of torrent hashes
   */
  hashes: Array<string>;
};

/**
 * Request body for creating a new bangumi
 */
export type CreateBangumi = {
  /**
   * First air date (YYYY-MM-DD format)
   */
  air_date?: string | null;
  /**
   * Day of week when new episodes air (0=Sunday, 1=Monday, ..., 6=Saturday)
   */
  air_week?: number | null;
  /**
   * Auto download new episodes
   */
  auto_download?: boolean;
  /**
   * Bangumi.tv ID
   */
  bgmtv_id?: number | null;
  /**
   * Episode offset
   */
  episode_offset?: number;
  /**
   * Whether the bangumi has finished airing
   */
  finished?: boolean;
  /**
   * Kind of bangumi (e.g., TV, Movie, OVA)
   */
  kind?: string | null;
  /**
   * Poster URL
   */
  poster_url?: string | null;
  /**
   * RSS subscriptions to create with this bangumi
   */
  rss_entries?: Array<RssEntry>;
  /**
   * Custom save path
   */
  save_path?: string | null;
  /**
   * Season number (default: 1)
   */
  season?: number;
  /**
   * Source type
   */
  source_type?: SourceType;
  /**
   * Chinese title (required)
   */
  title_chinese: string;
  /**
   * Japanese original name
   */
  title_japanese?: string | null;
  /**
   * Original Chinese title (native language, required, unique)
   */
  title_original_chinese: string;
  /**
   * Original Japanese title
   */
  title_original_japanese?: string | null;
  /**
   * TMDB ID
   */
  tmdb_id?: number | null;
  /**
   * Total episodes
   */
  total_episodes?: number;
  /**
   * Year (required)
   */
  year: number;
};

/**
 * Request to delete torrents
 */
export type DeleteTorrentsRequest = {
  /**
   * Whether to delete downloaded files (default: true)
   */
  delete_files?: boolean;
  /**
   * List of torrent hashes
   */
  hashes: Array<string>;
};

/**
 * Downloader configuration (supports qBittorrent)
 */
export type DownloaderSettings = {
  /**
   * Password (qBittorrent)
   */
  password?: string;
  /**
   * Default save path for downloads
   */
  save_path?: string;
  /**
   * Downloader type: qbittorrent
   */
  type?: DownloaderType;
  /**
   * Downloader Web UI URL (e.g., http://localhost:8080)
   */
  url?: string;
  /**
   * Username (qBittorrent)
   */
  username?: string;
  /**
   * Webhook URL for torrent completion callback (e.g., http://192.168.1.100:3000)
   * Used to configure qBittorrent's autorun to call back when downloads complete
   */
  webhook_url?: string;
};

/**
 * Downloader type
 */
export type DownloaderType = "qBittorrent";

/**
 * Episode item
 */
export type Episode = {
  /**
   * Air date
   */
  airdate: string;
  /**
   * Episode number
   */
  ep?: number | null;
  id: number;
  /**
   * Original name
   */
  name: string;
  /**
   * Chinese name
   */
  name_cn: string;
  /**
   * Sort order
   */
  sort: number;
  /**
   * Episode type: 0=本篇, 1=SP, 2=OP, 3=ED
   */
  type: EpisodeType;
};

/**
 * Episode type
 */
export type EpisodeType = "Main" | "Special" | "Opening" | "Ending";

/**
 * Filter configuration
 */
export type FilterSettings = {
  /**
   * Global RSS filters (regex patterns to exclude)
   */
  global_rss_filters?: Array<string>;
};

/**
 * System log entity
 */
export type Log = {
  created_at: string;
  id: number;
  /**
   * 日志级别: info, warning, error
   */
  level: LogLevel;
  /**
   * 日志消息
   */
  message: string;
};

/**
 * Log severity level
 */
export type LogLevel = "info" | "warning" | "error";

/**
 * RSS subscription entity
 */
export type Rss = {
  /**
   * Foreign key to bangumi
   */
  bangumi_id: number;
  created_at: string;
  /**
   * Whether subscription is enabled
   */
  enabled: boolean;
  /**
   * Regex patterns to exclude from matching
   */
  exclude_filters: Array<string>;
  id: number;
  /**
   * Whether this is the primary RSS source (only one per bangumi)
   * Episodes from primary RSS can override those from backup RSS
   */
  is_primary: boolean;
  updated_at: string;
  /**
   * RSS feed URL
   */
  url: string;
};

/**
 * RSS entry for creating bangumi with subscriptions
 */
export type RssEntry = {
  /**
   * Regex patterns to exclude from matching
   */
  filters?: Array<string>;
  /**
   * Whether this is the primary RSS source (default: false)
   */
  is_primary?: boolean;
  /**
   * RSS feed URL
   */
  url: string;
};

export type SearchResult = {
  id: string;
  name: string;
};

/**
 * Search response from POST /v0/search/subjects
 */
export type SearchSubjectsResponse = {
  data: Array<Subject>;
  limit: number;
  offset: number;
  total: number;
};

/**
 * Server state from sync maindata
 */
export type ServerState = {
  /**
   * Total downloaded data (bytes)
   */
  dl_info_data?: number | null;
  /**
   * Global download speed (bytes/s)
   */
  dl_info_speed?: number | null;
  /**
   * Total uploaded data (bytes)
   */
  up_info_data?: number | null;
  /**
   * Global upload speed (bytes/s)
   */
  up_info_speed?: number | null;
};

/**
 * Application settings stored in TOML file
 */
export type Settings = {
  /**
   * Downloader configuration
   */
  downloader?: DownloaderSettings;
  /**
   * Filter configuration
   */
  filter?: FilterSettings;
};

/**
 * Source type for bangumi
 */
export type SourceType = "webrip" | "bdrip";

export type Subgroup = {
  episodes: Array<Episode>;
  id: string;
  name: string;
  rss_url: string;
};

/**
 * Subject item in search results
 */
export type Subject = {
  date: string;
  eps: number;
  id: number;
  image: string;
  images: SubjectImages;
  name: string;
  name_cn: string;
  platform: string;
};

/**
 * Subject images from BGM.tv API
 */
export type SubjectImages = {
  common: string;
  grid: string;
  large: string;
  medium: string;
  small: string;
};

/**
 * Sync maindata response from qBittorrent
 * Used for incremental updates - only changed fields are included
 */
export type SyncMainData = {
  /**
   * Whether this is a full update (true) or incremental (false)
   */
  full_update?: boolean;
  /**
   * Response ID for incremental updates
   * Pass this value in subsequent requests to get only changes
   */
  rid: number;
  server_state?: null | ServerState;
  /**
   * Torrent data - hash -> partial torrent info
   * In incremental mode, only changed torrents are included
   */
  torrents?: {
    [key: string]: SyncTorrentInfo;
  };
  /**
   * List of removed torrent hashes (incremental updates only)
   */
  torrents_removed?: Array<string>;
};

/**
 * Partial torrent info for sync API
 * All fields are optional because incremental updates only include changed fields
 */
export type SyncTorrentInfo = {
  /**
   * Time when torrent was added (Unix timestamp)
   */
  added_on?: number | null;
  /**
   * Category
   */
  category?: string | null;
  /**
   * Time when torrent completed (Unix timestamp)
   */
  completion_on?: number | null;
  /**
   * Content path
   */
  content_path?: string | null;
  /**
   * Download speed (bytes/s)
   */
  dlspeed?: number | null;
  /**
   * Amount of data downloaded (bytes)
   */
  downloaded?: number | null;
  /**
   * Torrent ETA (seconds)
   */
  eta?: number | null;
  /**
   * Torrent name
   */
  name?: string | null;
  /**
   * Number of leechers
   */
  num_leechs?: number | null;
  /**
   * Number of seeds
   */
  num_seeds?: number | null;
  /**
   * Torrent progress (0.0 to 1.0)
   */
  progress?: number | null;
  /**
   * Share ratio
   */
  ratio?: number | null;
  /**
   * Full path to the torrent's download location
   */
  save_path?: string | null;
  /**
   * Torrent total size (bytes)
   */
  size?: number | null;
  /**
   * Torrent state
   */
  state?: string | null;
  /**
   * Tags (comma separated)
   */
  tags?: string | null;
  /**
   * Upload speed (bytes/s)
   */
  upspeed?: number | null;
};

/**
 * Request body for testing downloader connection
 */
export type TestDownloaderRequest = {
  /**
   * Password
   */
  password: string;
  /**
   * Downloader type (e.g., "qbittorrent")
   */
  type: DownloaderType;
  /**
   * Downloader Web UI URL
   */
  url: string;
  /**
   * Username
   */
  username: string;
};

/**
 * Torrent information from qBittorrent
 */
export type TorrentInfo = {
  /**
   * Amount of data downloaded (bytes)
   */
  downloaded: number;
  /**
   * Torrent ETA (seconds)
   */
  eta: number;
  /**
   * Torrent hash
   */
  hash: string;
  /**
   * Torrent name
   */
  name: string;
  /**
   * Torrent progress (0.0 to 1.0)
   */
  progress: number;
  /**
   * Full path to the torrent's download location
   */
  save_path: string;
  /**
   * Torrent total size (bytes)
   */
  size: number;
  /**
   * Torrent state (downloading, uploading, pausedDL, pausedUP, stalledDL, stalledUP, checkingDL, checkingUP, completed, etc.)
   */
  state: string;
};

export type TvShow = {
  backdrop_path?: string | null;
  first_air_date?: string | null;
  genre_ids: Array<number>;
  id: number;
  name: string;
  origin_country: Array<string>;
  original_language: string;
  original_name: string;
  overview: string;
  popularity: number;
  poster_path?: string | null;
  vote_average: number;
  vote_count: number;
};

/**
 * Request body for updating a bangumi with RSS entries
 */
export type UpdateBangumiRequest = {
  /**
   * Auto download new episodes
   */
  auto_download?: boolean | null;
  /**
   * Episode offset
   */
  episode_offset?: number | null;
  /**
   * RSS entries to sync (replaces all existing entries)
   */
  rss_entries?: Array<RssEntry> | null;
  /**
   * Custom save path (send null to clear)
   */
  save_path?: string | null;
};

/**
 * Request body for updating downloader settings
 */
export type UpdateDownloaderSettings = {
  /**
   * Password (send null to clear)
   */
  password?: string | null;
  /**
   * Default save path for downloads (send null to clear)
   */
  save_path?: string | null;
  type?: null | DownloaderType;
  /**
   * Downloader Web UI URL (send null to clear)
   */
  url?: string | null;
  /**
   * Username (send null to clear)
   */
  username?: string | null;
  /**
   * Webhook URL for torrent completion callback (send null to clear)
   */
  webhook_url?: string | null;
};

/**
 * Request body for updating filter settings
 */
export type UpdateFilterSettings = {
  /**
   * Global RSS filters (replaces entire array if provided)
   */
  global_rss_filters?: Array<string> | null;
};

/**
 * Request body for updating settings.
 * All fields are optional - only provided fields will be updated.
 */
export type UpdateSettings = {
  downloader?: null | UpdateDownloaderSettings;
  filter?: null | UpdateFilterSettings;
};

export type GetBangumiData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/bangumi";
};

export type GetBangumiErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetBangumiResponses = {
  /**
   * List of all bangumi
   */
  200: Array<Bangumi>;
};

export type GetBangumiResponse = GetBangumiResponses[keyof GetBangumiResponses];

export type CreateBangumiData = {
  body: CreateBangumi;
  path?: never;
  query?: never;
  url: "/api/bangumi";
};

export type CreateBangumiErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type CreateBangumiResponses = {
  /**
   * Bangumi created successfully
   */
  201: Bangumi;
};

export type CreateBangumiResponse =
  CreateBangumiResponses[keyof CreateBangumiResponses];

export type GetBangumiByIdData = {
  body?: never;
  path: {
    /**
     * Bangumi ID
     */
    id: number;
  };
  query?: never;
  url: "/api/bangumi/{id}";
};

export type GetBangumiByIdErrors = {
  /**
   * Bangumi not found
   */
  404: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetBangumiByIdResponses = {
  /**
   * Bangumi with RSS subscriptions
   */
  200: BangumiWithRss;
};

export type GetBangumiByIdResponse =
  GetBangumiByIdResponses[keyof GetBangumiByIdResponses];

export type UpdateBangumiData = {
  body: UpdateBangumiRequest;
  path: {
    /**
     * Bangumi ID
     */
    id: number;
  };
  query?: never;
  url: "/api/bangumi/{id}";
};

export type UpdateBangumiErrors = {
  /**
   * Bangumi not found
   */
  404: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type UpdateBangumiResponses = {
  /**
   * Bangumi updated successfully
   */
  200: BangumiWithRss;
};

export type UpdateBangumiResponse =
  UpdateBangumiResponses[keyof UpdateBangumiResponses];

export type TestDownloaderConnectionData = {
  body: TestDownloaderRequest;
  path?: never;
  query?: never;
  url: "/api/downloader/test";
};

export type TestDownloaderConnectionErrors = {
  /**
   * Authentication failed
   */
  401: unknown;
  /**
   * Connection error
   */
  500: unknown;
};

export type TestDownloaderConnectionResponses = {
  /**
   * Connection successful
   */
  200: unknown;
};

export type GetEpisodesData = {
  body?: never;
  path: {
    /**
     * BGM.tv subject ID
     */
    subject_id: number;
  };
  query?: never;
  url: "/api/episodes/{subject_id}";
};

export type GetEpisodesErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetEpisodesResponses = {
  /**
   * Episodes list
   */
  200: Array<Episode>;
};

export type GetEpisodesResponse =
  GetEpisodesResponses[keyof GetEpisodesResponses];

export type CleanupLogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/logs";
};

export type CleanupLogsErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type CleanupLogsResponses = {
  /**
   * Old logs deleted
   */
  200: number;
};

export type CleanupLogsResponse =
  CleanupLogsResponses[keyof CleanupLogsResponses];

export type GetLogsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by log level
     */
    level?: string | null;
    /**
     * Maximum number of logs to return (default: 50, max: 500)
     */
    limit?: number | null;
    /**
     * Number of logs to skip (for pagination)
     */
    offset?: number | null;
  };
  url: "/api/logs";
};

export type GetLogsErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetLogsResponses = {
  /**
   * Logs retrieved successfully
   */
  200: Array<Log>;
};

export type GetLogsResponse = GetLogsResponses[keyof GetLogsResponses];

export type StreamLogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/logs/stream";
};

export type StreamLogsResponses = {
  /**
   * SSE log stream
   */
  200: unknown;
};

export type GetMikanRssData = {
  body?: never;
  path?: never;
  query: {
    /**
     * ID to lookup
     */
    id: string;
  };
  url: "/api/mikan/rss";
};

export type GetMikanRssErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetMikanRssResponses = {
  /**
   * Bangumi detail with subgroups and RSS URLs
   */
  200: BangumiDetail;
};

export type GetMikanRssResponse =
  GetMikanRssResponses[keyof GetMikanRssResponses];

export type TriggerRssFetchData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/scheduler/rss-fetch";
};

export type TriggerRssFetchErrors = {
  /**
   * Job execution failed
   */
  500: unknown;
};

export type TriggerRssFetchResponses = {
  /**
   * RSS fetch job triggered successfully
   */
  200: unknown;
};

export type SearchBgmtvData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
  };
  url: "/api/search/bgmtv";
};

export type SearchBgmtvErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type SearchBgmtvResponses = {
  /**
   * Search results
   */
  200: Array<Subject>;
};

export type SearchBgmtvResponse =
  SearchBgmtvResponses[keyof SearchBgmtvResponses];

export type SearchMikanData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
  };
  url: "/api/search/mikan";
};

export type SearchMikanErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type SearchMikanResponses = {
  /**
   * Search results from Mikan
   */
  200: Array<SearchResult>;
};

export type SearchMikanResponse =
  SearchMikanResponses[keyof SearchMikanResponses];

export type SearchTmdbData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
  };
  url: "/api/search/tmdb";
};

export type SearchTmdbErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type SearchTmdbResponses = {
  /**
   * Search results from TMDB
   */
  200: Array<TvShow>;
};

export type SearchTmdbResponse = SearchTmdbResponses[keyof SearchTmdbResponses];

export type GetSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/settings";
};

export type GetSettingsErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetSettingsResponses = {
  /**
   * Application settings
   */
  200: Settings;
};

export type GetSettingsResponse =
  GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
  body: UpdateSettings;
  path?: never;
  query?: never;
  url: "/api/settings";
};

export type UpdateSettingsErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type UpdateSettingsResponses = {
  /**
   * Settings updated successfully
   */
  200: Settings;
};

export type UpdateSettingsResponse =
  UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type ResetSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/settings/reset";
};

export type ResetSettingsErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type ResetSettingsResponses = {
  /**
   * Settings reset successfully
   */
  200: Settings;
};

export type ResetSettingsResponse =
  ResetSettingsResponses[keyof ResetSettingsResponses];

export type ListTorrentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/torrents";
};

export type ListTorrentsErrors = {
  /**
   * Downloader not configured
   */
  400: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type ListTorrentsResponses = {
  /**
   * List of all torrents
   */
  200: Array<TorrentInfo>;
};

export type ListTorrentsResponse =
  ListTorrentsResponses[keyof ListTorrentsResponses];

export type DeleteTorrentsData = {
  body: DeleteTorrentsRequest;
  path?: never;
  query?: never;
  url: "/api/torrents/delete";
};

export type DeleteTorrentsErrors = {
  /**
   * Invalid request (empty hashes) or downloader not configured
   */
  400: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type DeleteTorrentsResponses = {
  /**
   * Torrents deleted successfully
   */
  200: unknown;
};

export type PauseTorrentsData = {
  body: ControlTorrentsRequest;
  path?: never;
  query?: never;
  url: "/api/torrents/pause";
};

export type PauseTorrentsErrors = {
  /**
   * Invalid request (empty hashes) or downloader not configured
   */
  400: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type PauseTorrentsResponses = {
  /**
   * Torrents paused successfully
   */
  200: unknown;
};

export type ResumeTorrentsData = {
  body: ControlTorrentsRequest;
  path?: never;
  query?: never;
  url: "/api/torrents/resume";
};

export type ResumeTorrentsErrors = {
  /**
   * Invalid request (empty hashes) or downloader not configured
   */
  400: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type ResumeTorrentsResponses = {
  /**
   * Torrents resumed successfully
   */
  200: unknown;
};

export type SyncMaindataData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Response ID from previous request. Use 0 for initial request.
     */
    rid?: number;
  };
  url: "/api/torrents/sync";
};

export type SyncMaindataErrors = {
  /**
   * Downloader not configured
   */
  400: unknown;
  /**
   * Internal server error
   */
  500: unknown;
};

export type SyncMaindataResponses = {
  /**
   * Sync maindata with torrent updates
   */
  200: SyncMainData;
};

export type SyncMaindataResponse =
  SyncMaindataResponses[keyof SyncMaindataResponses];

export type TorrentCompletedData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Torrent info hash from qBittorrent
     */
    hash: string;
    /**
     * Torrent name
     */
    name: string;
  };
  url: "/api/webhook/torrent-completed";
};

export type TorrentCompletedErrors = {
  /**
   * Torrent not found
   */
  404: unknown;
  /**
   * Failed to process torrent
   */
  500: unknown;
};

export type TorrentCompletedResponses = {
  /**
   * File renamed successfully
   */
  200: unknown;
};
