// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:3000" | (string & {});
};

/**
 * Bangumi (anime) subscription entity
 * Stores user's subscription state and download configuration
 */
export type Bangumi = {
  /**
   * Only download first matching episode per RSS check
   */
  auto_complete: boolean;
  created_at: string;
  /**
   * Current downloaded episode
   */
  current_episode: number;
  /**
   * Episode offset
   */
  episode_offset: number;
  id: number;
  /**
   * Reference to metadata (foreign key)
   */
  metadata_id: number;
  /**
   * Save path (required)
   */
  save_path: string;
  /**
   * Source type: webrip or bdrip
   */
  source_type: SourceType;
  updated_at: string;
};

export type BangumiDetail = {
  bgmtv_id?: number | null;
  subgroups: Array<Subgroup>;
};

/**
 * Bangumi with its associated metadata
 */
export type BangumiWithMetadata = Bangumi & {
  /**
   * Associated metadata
   */
  metadata: Metadata;
};

/**
 * Bangumi with metadata and RSS subscriptions
 */
export type BangumiWithRss = Bangumi & {
  /**
   * Associated metadata
   */
  metadata: Metadata;
  /**
   * RSS subscriptions for this bangumi
   */
  rss_entries: Array<Rss>;
};

/**
 * Calendar day with weekday info and items
 */
export type CalendarDay = {
  items: Array<CalendarSubject>;
  weekday: Weekday;
};

/**
 * Subject item in calendar results
 */
export type CalendarSubject = {
  /**
   * First air date (YYYY-MM-DD)
   */
  air_date?: string | null;
  /**
   * Day of week (0=Sunday, 1-6=Mon-Sat)
   */
  air_week: number;
  /**
   * BGM.tv subject ID
   */
  bgmtv_id?: number | null;
  /**
   * Mikan bangumi ID
   */
  mikan_id?: string | null;
  /**
   * Parsed Chinese title (without season info)
   */
  parsed_name: string;
  /**
   * Platform type (tv, movie, ova)
   */
  platform: Platform;
  /**
   * Poster image URL
   */
  poster_url?: string | null;
  /**
   * Parsed season number (defaults to 1)
   */
  season: number;
  /**
   * Chinese title
   */
  title_chinese: string;
  /**
   * Japanese title
   */
  title_japanese?: string | null;
  /**
   * Total episodes
   */
  total_episodes: number;
};

/**
 * Request body for creating a new bangumi
 */
export type CreateBangumi = {
  /**
   * Only download first matching episode per RSS check
   */
  auto_complete?: boolean;
  /**
   * Episode offset
   */
  episode_offset?: number;
  metadata?: null | CreateMetadata;
  /**
   * Metadata ID (if using existing metadata)
   */
  metadata_id?: number | null;
  /**
   * RSS subscriptions to create with this bangumi
   */
  rss_entries?: Array<RssEntry>;
  /**
   * Source type
   */
  source_type?: SourceType;
};

/**
 * Request body for creating new metadata
 */
export type CreateMetadata = {
  /**
   * First air date (YYYY-MM-DD format)
   */
  air_date?: string | null;
  /**
   * Day of week when new episodes air (0=Sunday ~ 6=Saturday)
   */
  air_week: number;
  /**
   * BGM.tv subject ID
   */
  bgmtv_id?: number | null;
  /**
   * Whether the anime has finished airing
   */
  finished?: boolean;
  /**
   * Mikan bangumi ID
   */
  mikan_id?: string | null;
  /**
   * Platform type (TV, Movie, OVA)
   */
  platform?: Platform;
  /**
   * Poster image URL
   */
  poster_url?: string | null;
  /**
   * Season number (default: 1)
   */
  season?: number;
  /**
   * Chinese title (required)
   */
  title_chinese: string;
  /**
   * Japanese original name
   */
  title_japanese?: string | null;
  /**
   * TMDB ID
   */
  tmdb_id?: number | null;
  /**
   * Total episodes
   */
  total_episodes?: number;
  /**
   * Year (required)
   */
  year: number;
};

/**
 * Request to delete torrents
 */
export type DeleteTorrentsRequest = {
  /**
   * Whether to delete downloaded files (default: true)
   */
  delete_files?: boolean;
  /**
   * List of torrent hashes
   */
  hashes: Array<string>;
};

/**
 * Per-downloader configurations
 */
export type DownloaderConfigs = {
  /**
   * qBittorrent configuration
   */
  qbittorrent?: QBittorrentConfig;
  /**
   * Transmission configuration
   */
  transmission?: TransmissionConfig;
};

/**
 * Downloader configuration with per-type configs
 */
export type DownloaderSettings = {
  /**
   * Per-downloader configurations
   */
  configs?: DownloaderConfigs;
  /**
   * Default save path for downloads (shared across all downloaders)
   */
  save_path?: string;
  /**
   * Currently active downloader type
   */
  type?: DownloaderType;
};

/**
 * Downloader type
 */
export type DownloaderType = "qBittorrent" | "Transmission";

/**
 * Episode item
 */
export type Episode = {
  /**
   * Air date
   */
  airdate: string;
  /**
   * Episode number
   */
  ep?: number | null;
  id: number;
  /**
   * Original name
   */
  name: string;
  /**
   * Chinese name
   */
  name_cn: string;
  /**
   * Sort order
   */
  sort: number;
  /**
   * Episode type: 0=本篇, 1=SP, 2=OP, 3=ED
   */
  type: EpisodeType;
};

/**
 * Episode type
 */
export type EpisodeType = "Main" | "Special" | "Opening" | "Ending";

/**
 * Filter configuration
 */
export type FilterSettings = {
  /**
   * Global RSS filters (regex patterns to exclude)
   */
  global_rss_filters?: Array<string>;
};

/**
 * System log entity
 */
export type Log = {
  created_at: string;
  id: number;
  /**
   * 日志级别: info, warning, error
   */
  level: LogLevel;
  /**
   * 日志消息
   */
  message: string;
};

/**
 * Log severity level
 */
export type LogLevel = "info" | "warning" | "error";

/**
 * Metadata entity for anime information
 * Unified metadata center caching data from BGM.tv, TMDB, and Mikan
 */
export type Metadata = {
  /**
   * First air date (YYYY-MM-DD format)
   */
  air_date?: string | null;
  /**
   * Day of week when new episodes air (0=Sunday ~ 6=Saturday)
   */
  air_week: number;
  /**
   * BGM.tv subject ID
   */
  bgmtv_id?: number | null;
  created_at: string;
  /**
   * Whether the anime has finished airing
   */
  finished: boolean;
  id: number;
  /**
   * Mikan bangumi ID
   */
  mikan_id?: string | null;
  /**
   * Platform type (TV, Movie, OVA)
   */
  platform: Platform;
  /**
   * Poster image URL
   */
  poster_url?: string | null;
  /**
   * Season number
   */
  season: number;
  /**
   * Chinese title (primary display)
   */
  title_chinese: string;
  /**
   * Japanese original name
   */
  title_japanese?: string | null;
  /**
   * TMDB ID
   */
  tmdb_id?: number | null;
  /**
   * Total episodes (0=unknown)
   */
  total_episodes: number;
  updated_at: string;
  /**
   * Year
   */
  year: number;
};

/**
 * Notification configuration
 */
export type NotificationSettings = {
  /**
   * Global enable/disable for notifications
   */
  enabled?: boolean;
  /**
   * Telegram configuration
   */
  telegram?: TelegramConfig;
};

/**
 * Parsed BGM.tv subject with extracted season info
 */
export type ParsedSubject = {
  /**
   * Release date
   */
  date: string;
  /**
   * Total episodes
   */
  eps: number;
  id: number;
  /**
   * Poster image URL
   */
  image: string;
  /**
   * Original name (Japanese)
   */
  name: string;
  /**
   * Chinese name
   */
  name_cn: string;
  /**
   * Parsed Chinese name (without season info)
   */
  parsed_name: string;
  /**
   * Platform (TV, Movie, OVA)
   */
  platform: string;
  /**
   * Parsed season number (defaults to 1)
   */
  season: number;
};

/**
 * Platform type for bangumi (TV, Movie, OVA)
 */
export type Platform = "tv" | "movie" | "ova";

/**
 * Priority configuration for torrent selection and washing
 */
export type PrioritySettings = {
  /**
   * Subtitle groups in priority order (first = highest priority)
   */
  subtitle_groups?: Array<string>;
  /**
   * Subtitle language combinations in priority order (first = highest priority)
   * Each entry is a set of languages that must exactly match
   * Example: [[CHS, JPN], [CHS, CHT, JPN], [CHT]]
   */
  subtitle_language_sets?: Array<SubtitleLanguageSet>;
};

/**
 * Proxy configuration for HTTP client
 */
export type ProxySettings = {
  /**
   * Proxy password (optional)
   */
  password?: string;
  /**
   * Proxy server URL (e.g., http://127.0.0.1:7890 or socks5://127.0.0.1:1080)
   */
  url?: string;
  /**
   * Proxy username (optional)
   */
  username?: string;
};

/**
 * qBittorrent-specific configuration
 */
export type QBittorrentConfig = {
  /**
   * Password (required)
   */
  password?: string;
  /**
   * Web UI URL (e.g., http://localhost:8080)
   */
  url?: string;
  /**
   * Username (required)
   */
  username?: string;
};

/**
 * RSS subscription entity
 */
export type Rss = {
  /**
   * Foreign key to bangumi
   */
  bangumi_id: number;
  created_at: string;
  /**
   * Whether subscription is enabled
   */
  enabled: boolean;
  /**
   * Regex patterns to exclude from matching
   */
  exclude_filters: Array<string>;
  /**
   * Optional subtitle group name
   */
  group?: string | null;
  id: number;
  /**
   * Regex patterns to include in matching
   */
  include_filters: Array<string>;
  /**
   * RSS subscription title: [group] {bangumi} S{season}
   */
  title: string;
  updated_at: string;
  /**
   * RSS feed URL
   */
  url: string;
};

/**
 * RSS entry for creating bangumi with subscriptions
 */
export type RssEntry = {
  /**
   * Regex patterns to exclude from matching
   */
  filters?: Array<string>;
  /**
   * Optional subtitle group name
   */
  group?: string | null;
  /**
   * Regex patterns to include in matching
   */
  include_filters?: Array<string>;
  /**
   * RSS feed URL
   */
  url: string;
};

export type SearchResult = {
  id: string;
  name: string;
};

/**
 * Search response from POST /v0/search/subjects
 */
export type SearchSubjectsResponse = {
  data: Array<Subject>;
  limit: number;
  offset: number;
  total: number;
};

export type Season = "winter" | "spring" | "summer" | "fall";

/**
 * Application settings stored in TOML file
 */
export type Settings = {
  /**
   * Downloader configuration
   */
  downloader?: DownloaderSettings;
  /**
   * Filter configuration
   */
  filter?: FilterSettings;
  /**
   * Notification configuration
   */
  notification?: NotificationSettings;
  /**
   * Priority configuration for torrent selection and washing
   */
  priority?: PrioritySettings;
  /**
   * Proxy configuration for HTTP client
   */
  proxy?: ProxySettings;
};

/**
 * Source type for bangumi
 */
export type SourceType = "webrip" | "bdrip";

/**
 * 字幕类型枚举
 */
export type SubType = "CHS" | "CHT" | "JPN" | "ENG" | "UNKNOWN";

export type Subgroup = {
  episodes: Array<Episode>;
  id: string;
  name: string;
  rss_url: string;
};

/**
 * Subject item in search results
 */
export type Subject = {
  date: string;
  eps: number;
  id: number;
  image: string;
  images: SubjectImages;
  name: string;
  name_cn: string;
  platform: string;
};

/**
 * Subject images from BGM.tv API
 */
export type SubjectImages = {
  common: string;
  grid: string;
  large: string;
  medium: string;
  small: string;
};

/**
 * BGM.tv subject type
 */
export type SubjectType = "Book" | "Anime" | "Music" | "Game" | "Real";

/**
 * A normalized set of subtitle languages for exact matching.
 *
 * Languages are automatically sorted and deduplicated on creation,
 * ensuring that `[Chs, Jpn]` and `[Jpn, Chs]` are treated as equal.
 *
 * Serializes as a simple array of SubType (e.g., `["CHS", "JPN"]`).
 */
export type SubtitleLanguageSet = Array<SubType>;

/**
 * Unified download task representation.
 *
 * This model represents a download task across different downloaders,
 * normalizing fields into a common structure.
 */
export type Task = {
  /**
   * Category (optional, some downloaders support this)
   */
  category?: string | null;
  /**
   * Downloaded bytes
   */
  downloaded: number;
  /**
   * Estimated time to completion (seconds, -1 if unknown)
   */
  eta: number;
  /**
   * Unique identifier (hash for BitTorrent, ID for HTTP)
   */
  id: string;
  /**
   * Task name
   */
  name: string;
  /**
   * Download progress (0.0 to 1.0)
   */
  progress: number;
  /**
   * Save path / download directory
   */
  save_path: string;
  /**
   * Current status
   */
  status: TaskStatus;
  /**
   * Tags (comma-separated string for consistency)
   */
  tags: string;
  /**
   * Total size in bytes
   */
  total_size: number;
};

/**
 * Download task status.
 *
 * Normalized across different downloader implementations.
 */
export type TaskStatus =
  | "queued"
  | "downloading"
  | "paused"
  | "seeding"
  | "completed"
  | "stalled"
  | "checking"
  | "error"
  | "unknown";

/**
 * Telegram notification configuration
 */
export type TelegramConfig = {
  /**
   * Telegram Bot API token
   */
  bot_token?: string;
  /**
   * Telegram chat ID to send notifications to
   */
  chat_id?: string;
  /**
   * Enable Telegram notifications
   */
  enabled?: boolean;
};

/**
 * Request body for testing downloader connection
 */
export type TestDownloaderRequest = {
  /**
   * Password
   */
  password: string;
  /**
   * Downloader type (e.g., "qbittorrent")
   */
  type: DownloaderType;
  /**
   * Downloader Web UI URL
   */
  url: string;
  /**
   * Username
   */
  username: string;
};

/**
 * Request body for testing Telegram notification
 */
export type TestNotificationRequest = {
  /**
   * Telegram Bot API token
   */
  bot_token: string;
  /**
   * Telegram chat ID
   */
  chat_id: string;
};

/**
 * Request body for testing proxy connection
 */
export type TestProxyRequest = {
  /**
   * Proxy password (optional)
   */
  password?: string | null;
  /**
   * Proxy server URL (e.g., http://127.0.0.1:7890)
   */
  url: string;
  /**
   * Proxy username (optional)
   */
  username?: string | null;
};

export type TorrentSearchResult = {
  info_hash: string;
  source: TorrentSource;
  title: string;
  torrent_url: string;
};

export type TorrentSource = "mikan" | "nyaa";

/**
 * Transmission-specific configuration
 */
export type TransmissionConfig = {
  /**
   * Password (optional)
   */
  password?: string;
  /**
   * RPC URL (e.g., http://localhost:9091/transmission/rpc)
   */
  url?: string;
  /**
   * Username (optional)
   */
  username?: string;
};

export type TvShow = {
  backdrop_path?: string | null;
  first_air_date?: string | null;
  genre_ids: Array<number>;
  id: number;
  name: string;
  origin_country: Array<string>;
  original_language: string;
  original_name: string;
  overview: string;
  popularity: number;
  poster_path?: string | null;
  vote_average: number;
  vote_count: number;
};

/**
 * Request body for updating a bangumi with RSS entries
 */
export type UpdateBangumiRequest = {
  /**
   * Only download first matching episode per RSS check
   */
  auto_complete?: boolean | null;
  /**
   * Episode offset
   */
  episode_offset?: number | null;
  /**
   * RSS entries to sync (replaces all existing entries)
   */
  rss_entries?: Array<RssEntry> | null;
};

/**
 * Request body for updating downloader settings
 */
export type UpdateDownloaderSettings = {
  qbittorrent?: null | UpdateQBittorrentConfig;
  /**
   * Update shared save path (send null to clear)
   */
  save_path?: string | null;
  transmission?: null | UpdateTransmissionConfig;
  type?: null | DownloaderType;
};

/**
 * Request body for updating filter settings
 */
export type UpdateFilterSettings = {
  /**
   * Global RSS filters (replaces entire array if provided)
   */
  global_rss_filters?: Array<string> | null;
};

/**
 * Request body for updating metadata
 * For Clearable fields: null means clear the value, value means set new value, absent means unchanged
 */
export type UpdateMetadata = {
  /**
   * First air date in YYYY-MM-DD format (null to clear)
   */
  air_date?: string | null;
  /**
   * Day of week when new episodes air (0=Sunday ~ 6=Saturday)
   */
  air_week?: number | null;
  /**
   * BGM.tv subject ID (null to clear)
   */
  bgmtv_id?: number | null;
  /**
   * Whether the anime has finished airing
   */
  finished?: boolean | null;
  /**
   * Mikan bangumi ID (null to clear)
   */
  mikan_id?: string | null;
  platform?: null | Platform;
  /**
   * Poster image URL (null to clear)
   */
  poster_url?: string | null;
  /**
   * Season number
   */
  season?: number | null;
  /**
   * Chinese title
   */
  title_chinese?: string | null;
  /**
   * Japanese original name (null to clear)
   */
  title_japanese?: string | null;
  /**
   * TMDB ID (null to clear)
   */
  tmdb_id?: number | null;
  /**
   * Total episodes
   */
  total_episodes?: number | null;
  /**
   * Year
   */
  year?: number | null;
};

/**
 * Request body for updating notification settings
 */
export type UpdateNotificationSettings = {
  /**
   * Enable/disable notifications globally
   */
  enabled?: boolean | null;
  telegram?: null | UpdateTelegramConfig;
};

/**
 * Request body for updating priority settings
 */
export type UpdatePrioritySettings = {
  /**
   * Subtitle groups in priority order (replaces entire array if provided)
   */
  subtitle_groups?: Array<string> | null;
  /**
   * Subtitle language combinations in priority order (replaces entire array if provided)
   * Each entry is a set of languages that must exactly match
   */
  subtitle_language_sets?: Array<SubtitleLanguageSet> | null;
};

/**
 * Request body for updating proxy settings
 */
export type UpdateProxySettings = {
  /**
   * Password (send null to clear)
   */
  password?: string | null;
  /**
   * Proxy server URL (send null to clear)
   */
  url?: string | null;
  /**
   * Username (send null to clear)
   */
  username?: string | null;
};

/**
 * Request body for updating qBittorrent settings
 */
export type UpdateQBittorrentConfig = {
  /**
   * Password (send null to clear)
   */
  password?: string | null;
  /**
   * Web UI URL (send null to clear)
   */
  url?: string | null;
  /**
   * Username (send null to clear)
   */
  username?: string | null;
};

/**
 * Request body for updating settings.
 * All fields are optional - only provided fields will be updated.
 */
export type UpdateSettings = {
  downloader?: null | UpdateDownloaderSettings;
  filter?: null | UpdateFilterSettings;
  notification?: null | UpdateNotificationSettings;
  priority?: null | UpdatePrioritySettings;
  proxy?: null | UpdateProxySettings;
};

/**
 * Request body for updating Telegram settings
 */
export type UpdateTelegramConfig = {
  /**
   * Bot token (send null to clear)
   */
  bot_token?: string | null;
  /**
   * Chat ID (send null to clear)
   */
  chat_id?: string | null;
  /**
   * Enable Telegram notifications
   */
  enabled?: boolean | null;
};

/**
 * Request body for updating Transmission settings
 */
export type UpdateTransmissionConfig = {
  /**
   * Password (send null to clear)
   */
  password?: string | null;
  /**
   * RPC URL (send null to clear)
   */
  url?: string | null;
  /**
   * Username (send null to clear)
   */
  username?: string | null;
};

/**
 * Weekday info
 */
export type Weekday = {
  /**
   * Chinese name
   */
  cn: string;
  /**
   * English name
   */
  en: string;
  /**
   * Weekday ID (1=Mon, 7=Sun)
   */
  id: number;
  /**
   * Japanese name
   */
  ja: string;
};

export type GetBangumiData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/bangumi";
};

export type GetBangumiResponses = {
  /**
   * List of all bangumi
   */
  200: Array<BangumiWithMetadata>;
};

export type GetBangumiResponse = GetBangumiResponses[keyof GetBangumiResponses];

export type CreateBangumiData = {
  body: CreateBangumi;
  path?: never;
  query?: never;
  url: "/api/bangumi";
};

export type CreateBangumiResponses = {
  /**
   * Bangumi created successfully
   */
  201: BangumiWithMetadata;
};

export type CreateBangumiResponse =
  CreateBangumiResponses[keyof CreateBangumiResponses];

export type GetBangumiByIdData = {
  body?: never;
  path: {
    /**
     * Bangumi ID
     */
    id: number;
  };
  query?: never;
  url: "/api/bangumi/{id}";
};

export type GetBangumiByIdErrors = {
  /**
   * Bangumi not found
   */
  404: unknown;
};

export type GetBangumiByIdResponses = {
  /**
   * Bangumi with RSS subscriptions
   */
  200: BangumiWithRss;
};

export type GetBangumiByIdResponse =
  GetBangumiByIdResponses[keyof GetBangumiByIdResponses];

export type UpdateBangumiData = {
  body: UpdateBangumiRequest;
  path: {
    /**
     * Bangumi ID
     */
    id: number;
  };
  query?: never;
  url: "/api/bangumi/{id}";
};

export type UpdateBangumiErrors = {
  /**
   * Bangumi not found
   */
  404: unknown;
};

export type UpdateBangumiResponses = {
  /**
   * Bangumi updated successfully
   */
  200: BangumiWithRss;
};

export type UpdateBangumiResponse =
  UpdateBangumiResponses[keyof UpdateBangumiResponses];

export type GetCalendarData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Year (e.g., 2025). Defaults to current year.
     */
    year?: number | null;
    /**
     * Season: winter, spring, summer, fall. Defaults to current season.
     */
    season?: null | Season;
  };
  url: "/api/calendar";
};

export type GetCalendarResponses = {
  /**
   * Weekly anime schedule
   */
  200: Array<CalendarDay>;
};

export type GetCalendarResponse =
  GetCalendarResponses[keyof GetCalendarResponses];

export type RefreshCalendarData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Year (e.g., 2025). Defaults to current year.
     */
    year?: number | null;
    /**
     * Season: winter, spring, summer, fall. Defaults to current season.
     */
    season?: null | Season;
  };
  url: "/api/calendar/refresh";
};

export type RefreshCalendarResponses = {
  /**
   * Calendar refreshed successfully
   */
  200: Array<CalendarDay>;
};

export type RefreshCalendarResponse =
  RefreshCalendarResponses[keyof RefreshCalendarResponses];

export type TestDownloaderConnectionData = {
  body: TestDownloaderRequest;
  path?: never;
  query?: never;
  url: "/api/downloader/test";
};

export type TestDownloaderConnectionErrors = {
  /**
   * Authentication failed
   */
  401: unknown;
};

export type TestDownloaderConnectionResponses = {
  /**
   * Connection successful
   */
  200: unknown;
};

export type GetEpisodesData = {
  body?: never;
  path: {
    /**
     * BGM.tv subject ID
     */
    subject_id: number;
  };
  query?: never;
  url: "/api/episodes/{subject_id}";
};

export type GetEpisodesResponses = {
  /**
   * Episodes list
   */
  200: Array<Episode>;
};

export type GetEpisodesResponse =
  GetEpisodesResponses[keyof GetEpisodesResponses];

export type CleanupLogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/logs";
};

export type CleanupLogsResponses = {
  /**
   * Old logs deleted
   */
  200: number;
};

export type CleanupLogsResponse =
  CleanupLogsResponses[keyof CleanupLogsResponses];

export type GetLogsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by log level
     */
    level?: string | null;
    /**
     * Maximum number of logs to return (default: 50, max: 500)
     */
    limit?: number | null;
    /**
     * Number of logs to skip (for pagination)
     */
    offset?: number | null;
  };
  url: "/api/logs";
};

export type GetLogsResponses = {
  /**
   * Logs retrieved successfully
   */
  200: Array<Log>;
};

export type GetLogsResponse = GetLogsResponses[keyof GetLogsResponses];

export type StreamLogsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/logs/stream";
};

export type StreamLogsResponses = {
  /**
   * SSE log stream
   */
  200: unknown;
};

export type GetMetadataData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/metadata";
};

export type GetMetadataResponses = {
  /**
   * List of all metadata
   */
  200: Array<Metadata>;
};

export type GetMetadataResponse =
  GetMetadataResponses[keyof GetMetadataResponses];

export type GetMetadataByIdData = {
  body?: never;
  path: {
    /**
     * Metadata ID
     */
    id: number;
  };
  query?: never;
  url: "/api/metadata/{id}";
};

export type GetMetadataByIdErrors = {
  /**
   * Metadata not found
   */
  404: unknown;
};

export type GetMetadataByIdResponses = {
  /**
   * Metadata details
   */
  200: Metadata;
};

export type GetMetadataByIdResponse =
  GetMetadataByIdResponses[keyof GetMetadataByIdResponses];

export type UpdateMetadataData = {
  body: UpdateMetadata;
  path: {
    /**
     * Metadata ID
     */
    id: number;
  };
  query?: never;
  url: "/api/metadata/{id}";
};

export type UpdateMetadataErrors = {
  /**
   * Metadata not found
   */
  404: unknown;
};

export type UpdateMetadataResponses = {
  /**
   * Metadata updated successfully
   */
  200: Metadata;
};

export type UpdateMetadataResponse =
  UpdateMetadataResponses[keyof UpdateMetadataResponses];

export type GetMikanRssData = {
  body?: never;
  path?: never;
  query: {
    /**
     * ID to lookup
     */
    id: string;
  };
  url: "/api/mikan/rss";
};

export type GetMikanRssResponses = {
  /**
   * Bangumi detail with subgroups and RSS URLs
   */
  200: BangumiDetail;
};

export type GetMikanRssResponse =
  GetMikanRssResponses[keyof GetMikanRssResponses];

export type TestNotificationData = {
  body: TestNotificationRequest;
  path?: never;
  query?: never;
  url: "/api/notification/test";
};

export type TestNotificationErrors = {
  /**
   * Invalid configuration
   */
  400: unknown;
};

export type TestNotificationResponses = {
  /**
   * Notification sent successfully
   */
  200: unknown;
};

export type TestProxyData = {
  body: TestProxyRequest;
  path?: never;
  query?: never;
  url: "/api/proxy/test";
};

export type TestProxyErrors = {
  /**
   * Invalid proxy configuration
   */
  400: unknown;
};

export type TestProxyResponses = {
  /**
   * Proxy connection successful
   */
  200: unknown;
};

export type SearchBgmtvData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
  };
  url: "/api/search/bgmtv";
};

export type SearchBgmtvResponses = {
  /**
   * Search results
   */
  200: Array<ParsedSubject>;
};

export type SearchBgmtvResponse =
  SearchBgmtvResponses[keyof SearchBgmtvResponses];

export type SearchMikanData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
  };
  url: "/api/search/mikan";
};

export type SearchMikanResponses = {
  /**
   * Search results from Mikan
   */
  200: Array<SearchResult>;
};

export type SearchMikanResponse =
  SearchMikanResponses[keyof SearchMikanResponses];

export type SearchTmdbData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
  };
  url: "/api/search/tmdb";
};

export type SearchTmdbResponses = {
  /**
   * Search results from TMDB
   */
  200: Array<TvShow>;
};

export type SearchTmdbResponse = SearchTmdbResponses[keyof SearchTmdbResponses];

export type GetSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/settings";
};

export type GetSettingsResponses = {
  /**
   * Application settings
   */
  200: Settings;
};

export type GetSettingsResponse =
  GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
  body: UpdateSettings;
  path?: never;
  query?: never;
  url: "/api/settings";
};

export type UpdateSettingsResponses = {
  /**
   * Settings updated successfully
   */
  200: Settings;
};

export type UpdateSettingsResponse =
  UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type ResetSettingsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/settings/reset";
};

export type ResetSettingsResponses = {
  /**
   * Settings reset successfully
   */
  200: Settings;
};

export type ResetSettingsResponse =
  ResetSettingsResponses[keyof ResetSettingsResponses];

export type ListTorrentsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/torrents";
};

export type ListTorrentsErrors = {
  /**
   * Downloader not configured
   */
  400: unknown;
};

export type ListTorrentsResponses = {
  /**
   * List of all torrents
   */
  200: Array<Task>;
};

export type ListTorrentsResponse =
  ListTorrentsResponses[keyof ListTorrentsResponses];

export type DeleteTorrentsData = {
  body: DeleteTorrentsRequest;
  path?: never;
  query?: never;
  url: "/api/torrents/delete";
};

export type DeleteTorrentsErrors = {
  /**
   * Invalid request (empty hashes) or downloader not configured
   */
  400: unknown;
};

export type DeleteTorrentsResponses = {
  /**
   * Torrents deleted successfully
   */
  200: unknown;
};

export type SearchTorrentsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
    /**
     * Source to search from: "nyaa" (default) or "mikan"
     */
    source?: TorrentSource;
  };
  url: "/api/torrents/search";
};

export type SearchTorrentsResponses = {
  /**
   * Search results from the specified source
   */
  200: Array<TorrentSearchResult>;
};

export type SearchTorrentsResponse =
  SearchTorrentsResponses[keyof SearchTorrentsResponses];
