// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://127.0.0.1:3000" | (string & {});
};

/**
 * Bangumi (anime) main entity
 */
export type Bangumi = {
  /**
   * First air date (YYYY-MM-DD format)
   */
  air_date?: string | null;
  /**
   * Day of week when new episodes air (0=Sunday, 1=Monday, ..., 6=Saturday)
   */
  air_week?: number | null;
  /**
   * Auto download new episodes
   */
  auto_download: boolean;
  /**
   * Bangumi.tv ID
   */
  bgmtv_id?: number | null;
  created_at: string;
  /**
   * Current downloaded episode
   */
  current_episode: number;
  /**
   * Episode offset
   */
  episode_offset: number;
  /**
   * Whether the bangumi has finished airing
   */
  finished: boolean;
  id: number;
  /**
   * Kind of bangumi (e.g., TV, Movie, OVA)
   */
  kind?: string | null;
  /**
   * Poster URL
   */
  poster_url?: string | null;
  /**
   * Custom save path (None=use default)
   */
  save_path?: string | null;
  /**
   * Season number
   */
  season: number;
  /**
   * Source type: webrip or bdrip
   */
  source_type: SourceType;
  /**
   * Chinese title (primary display)
   */
  title_chinese: string;
  /**
   * Japanese original name
   */
  title_japanese?: string | null;
  /**
   * Original title (native language, required, unique)
   */
  title_original: string;
  /**
   * TMDB ID
   */
  tmdb_id?: number | null;
  /**
   * Total episodes (0=unknown)
   */
  total_episodes: number;
  updated_at: string;
  /**
   * Year
   */
  year: number;
};

export type BangumiDetail = {
  subgroups: Array<Subgroup>;
};

/**
 * Request body for creating a new bangumi
 */
export type CreateBangumi = {
  /**
   * First air date (YYYY-MM-DD format)
   */
  air_date?: string | null;
  /**
   * Day of week when new episodes air (0=Sunday, 1=Monday, ..., 6=Saturday)
   */
  air_week?: number | null;
  /**
   * Auto download new episodes
   */
  auto_download?: boolean;
  /**
   * Bangumi.tv ID
   */
  bgmtv_id?: number | null;
  /**
   * Episode offset
   */
  episode_offset?: number;
  /**
   * Whether the bangumi has finished airing
   */
  finished?: boolean;
  /**
   * Kind of bangumi (e.g., TV, Movie, OVA)
   */
  kind?: string | null;
  /**
   * Poster URL
   */
  poster_url?: string | null;
  /**
   * RSS subscriptions to create with this bangumi
   */
  rss_entries?: Array<RssEntry>;
  /**
   * Custom save path
   */
  save_path?: string | null;
  /**
   * Season number (default: 1)
   */
  season?: number;
  /**
   * Source type
   */
  source_type?: SourceType;
  /**
   * Chinese title (required)
   */
  title_chinese: string;
  /**
   * Japanese original name
   */
  title_japanese?: string | null;
  /**
   * Original title (native language, required, unique)
   */
  title_original: string;
  /**
   * TMDB ID
   */
  tmdb_id?: number | null;
  /**
   * Total episodes
   */
  total_episodes?: number;
  /**
   * Year (required)
   */
  year: number;
};

/**
 * Episode item
 */
export type Episode = {
  /**
   * Air date
   */
  airdate: string;
  /**
   * Episode number
   */
  ep?: number | null;
  id: number;
  /**
   * Original name
   */
  name: string;
  /**
   * Chinese name
   */
  name_cn: string;
  /**
   * Sort order
   */
  sort: number;
  /**
   * Episode type: 0=本篇, 1=SP, 2=OP, 3=ED
   */
  type: EpisodeType;
};

/**
 * Episode type
 */
export type EpisodeType = "Main" | "Special" | "Opening" | "Ending";

/**
 * RSS entry for creating bangumi with subscriptions
 */
export type RssEntry = {
  /**
   * Regex patterns to exclude from matching
   */
  filters?: Array<string>;
  /**
   * RSS feed URL
   */
  url: string;
};

export type SearchResult = {
  id: string;
  name: string;
};

/**
 * Search response from POST /v0/search/subjects
 */
export type SearchSubjectsResponse = {
  data: Array<Subject>;
  limit: number;
  offset: number;
  total: number;
};

/**
 * Source type for bangumi
 */
export type SourceType = "webrip" | "bdrip";

export type Subgroup = {
  episodes: Array<Episode>;
  id: string;
  name: string;
  rss_url: string;
};

/**
 * Subject item in search results
 */
export type Subject = {
  date?: string | null;
  eps: number;
  id: number;
  image?: string | null;
  name: string;
  name_cn: string;
  platform?: string | null;
};

export type TvShow = {
  backdrop_path?: string | null;
  first_air_date?: string | null;
  genre_ids: Array<number>;
  id: number;
  name: string;
  origin_country: Array<string>;
  original_language: string;
  original_name: string;
  overview: string;
  popularity: number;
  poster_path?: string | null;
  vote_average: number;
  vote_count: number;
};

export type GetBangumiData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/bangumi";
};

export type GetBangumiErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetBangumiResponses = {
  /**
   * List of all bangumi
   */
  200: Array<Bangumi>;
};

export type GetBangumiResponse = GetBangumiResponses[keyof GetBangumiResponses];

export type CreateBangumiData = {
  body: CreateBangumi;
  path?: never;
  query?: never;
  url: "/api/bangumi";
};

export type CreateBangumiErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type CreateBangumiResponses = {
  /**
   * Bangumi created successfully
   */
  201: Bangumi;
};

export type CreateBangumiResponse =
  CreateBangumiResponses[keyof CreateBangumiResponses];

export type GetEpisodesData = {
  body?: never;
  path: {
    /**
     * BGM.tv subject ID
     */
    subject_id: number;
  };
  query?: never;
  url: "/api/episodes/{subject_id}";
};

export type GetEpisodesErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetEpisodesResponses = {
  /**
   * Episodes list
   */
  200: Array<Episode>;
};

export type GetEpisodesResponse =
  GetEpisodesResponses[keyof GetEpisodesResponses];

export type GetMikanRssData = {
  body?: never;
  path?: never;
  query: {
    /**
     * ID to lookup
     */
    id: string;
  };
  url: "/api/mikan/rss";
};

export type GetMikanRssErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type GetMikanRssResponses = {
  /**
   * Bangumi detail with subgroups and RSS URLs
   */
  200: BangumiDetail;
};

export type GetMikanRssResponse =
  GetMikanRssResponses[keyof GetMikanRssResponses];

export type SearchBgmtvData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
  };
  url: "/api/search/bgmtv";
};

export type SearchBgmtvErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type SearchBgmtvResponses = {
  /**
   * Search results
   */
  200: Array<Subject>;
};

export type SearchBgmtvResponse =
  SearchBgmtvResponses[keyof SearchBgmtvResponses];

export type SearchMikanData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
  };
  url: "/api/search/mikan";
};

export type SearchMikanErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type SearchMikanResponses = {
  /**
   * Search results from Mikan
   */
  200: Array<SearchResult>;
};

export type SearchMikanResponse =
  SearchMikanResponses[keyof SearchMikanResponses];

export type SearchTmdbData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Keyword to search
     */
    keyword: string;
  };
  url: "/api/search/tmdb";
};

export type SearchTmdbErrors = {
  /**
   * Internal server error
   */
  500: unknown;
};

export type SearchTmdbResponses = {
  /**
   * Search results from TMDB
   */
  200: Array<TvShow>;
};

export type SearchTmdbResponse = SearchTmdbResponses[keyof SearchTmdbResponses];
