// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  createBangumi,
  getBangumi,
  getEpisodes,
  getMikanRss,
  type Options,
  searchBgmtv,
  searchMikan,
  searchTmdb,
} from "../sdk.gen";
import type {
  CreateBangumiData,
  CreateBangumiResponse,
  GetBangumiData,
  GetBangumiResponse,
  GetEpisodesData,
  GetEpisodesResponse,
  GetMikanRssData,
  GetMikanRssResponse,
  SearchBgmtvData,
  SearchBgmtvResponse,
  SearchMikanData,
  SearchMikanResponse,
  SearchTmdbData,
  SearchTmdbResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getBangumiQueryKey = (options?: Options<GetBangumiData>) =>
  createQueryKey("getBangumi", options);

/**
 * Get all bangumi
 */
export const getBangumiOptions = (options?: Options<GetBangumiData>) =>
  queryOptions<
    GetBangumiResponse,
    DefaultError,
    GetBangumiResponse,
    ReturnType<typeof getBangumiQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBangumi({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBangumiQueryKey(options),
  });

/**
 * Create a new bangumi
 */
export const createBangumiMutation = (
  options?: Partial<Options<CreateBangumiData>>,
): UseMutationOptions<
  CreateBangumiResponse,
  DefaultError,
  Options<CreateBangumiData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateBangumiResponse,
    DefaultError,
    Options<CreateBangumiData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createBangumi({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEpisodesQueryKey = (options: Options<GetEpisodesData>) =>
  createQueryKey("getEpisodes", options);

/**
 * Get episodes by subject ID from BGM.tv
 */
export const getEpisodesOptions = (options: Options<GetEpisodesData>) =>
  queryOptions<
    GetEpisodesResponse,
    DefaultError,
    GetEpisodesResponse,
    ReturnType<typeof getEpisodesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEpisodes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEpisodesQueryKey(options),
  });

export const getMikanRssQueryKey = (options: Options<GetMikanRssData>) =>
  createQueryKey("getMikanRss", options);

/**
 * Get bangumi detail with RSS URLs from Mikan
 */
export const getMikanRssOptions = (options: Options<GetMikanRssData>) =>
  queryOptions<
    GetMikanRssResponse,
    DefaultError,
    GetMikanRssResponse,
    ReturnType<typeof getMikanRssQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMikanRss({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMikanRssQueryKey(options),
  });

export const searchBgmtvQueryKey = (options: Options<SearchBgmtvData>) =>
  createQueryKey("searchBgmtv", options);

/**
 * Search for bangumi (Japanese anime) on BGM.tv
 */
export const searchBgmtvOptions = (options: Options<SearchBgmtvData>) =>
  queryOptions<
    SearchBgmtvResponse,
    DefaultError,
    SearchBgmtvResponse,
    ReturnType<typeof searchBgmtvQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchBgmtv({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchBgmtvQueryKey(options),
  });

export const searchMikanQueryKey = (options: Options<SearchMikanData>) =>
  createQueryKey("searchMikan", options);

/**
 * Search for bangumi on Mikan
 */
export const searchMikanOptions = (options: Options<SearchMikanData>) =>
  queryOptions<
    SearchMikanResponse,
    DefaultError,
    SearchMikanResponse,
    ReturnType<typeof searchMikanQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchMikan({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchMikanQueryKey(options),
  });

export const searchTmdbQueryKey = (options: Options<SearchTmdbData>) =>
  createQueryKey("searchTmdb", options);

/**
 * Search for anime on TMDB using discover API
 */
export const searchTmdbOptions = (options: Options<SearchTmdbData>) =>
  queryOptions<
    SearchTmdbResponse,
    DefaultError,
    SearchTmdbResponse,
    ReturnType<typeof searchTmdbQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchTmdb({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchTmdbQueryKey(options),
  });
