// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  createBangumi,
  getBangumi,
  getBangumiById,
  getEpisodes,
  getMikanRss,
  getSettings,
  type Options,
  resetSettings,
  searchBgmtv,
  searchMikan,
  searchTmdb,
  testDownloaderConnection,
  updateBangumi,
  updateSettings,
} from "../sdk.gen";
import type {
  CreateBangumiData,
  CreateBangumiResponse,
  GetBangumiByIdData,
  GetBangumiByIdResponse,
  GetBangumiData,
  GetBangumiResponse,
  GetEpisodesData,
  GetEpisodesResponse,
  GetMikanRssData,
  GetMikanRssResponse,
  GetSettingsData,
  GetSettingsResponse,
  ResetSettingsData,
  ResetSettingsResponse,
  SearchBgmtvData,
  SearchBgmtvResponse,
  SearchMikanData,
  SearchMikanResponse,
  SearchTmdbData,
  SearchTmdbResponse,
  TestDownloaderConnectionData,
  UpdateBangumiData,
  UpdateBangumiResponse,
  UpdateSettingsData,
  UpdateSettingsResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getBangumiQueryKey = (options?: Options<GetBangumiData>) =>
  createQueryKey("getBangumi", options);

/**
 * Get all bangumi
 */
export const getBangumiOptions = (options?: Options<GetBangumiData>) =>
  queryOptions<
    GetBangumiResponse,
    DefaultError,
    GetBangumiResponse,
    ReturnType<typeof getBangumiQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBangumi({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBangumiQueryKey(options),
  });

/**
 * Create a new bangumi
 */
export const createBangumiMutation = (
  options?: Partial<Options<CreateBangumiData>>,
): UseMutationOptions<
  CreateBangumiResponse,
  DefaultError,
  Options<CreateBangumiData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateBangumiResponse,
    DefaultError,
    Options<CreateBangumiData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createBangumi({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBangumiByIdQueryKey = (options: Options<GetBangumiByIdData>) =>
  createQueryKey("getBangumiById", options);

/**
 * Get a bangumi by ID with its RSS subscriptions
 */
export const getBangumiByIdOptions = (options: Options<GetBangumiByIdData>) =>
  queryOptions<
    GetBangumiByIdResponse,
    DefaultError,
    GetBangumiByIdResponse,
    ReturnType<typeof getBangumiByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBangumiById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBangumiByIdQueryKey(options),
  });

/**
 * Update a bangumi
 */
export const updateBangumiMutation = (
  options?: Partial<Options<UpdateBangumiData>>,
): UseMutationOptions<
  UpdateBangumiResponse,
  DefaultError,
  Options<UpdateBangumiData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateBangumiResponse,
    DefaultError,
    Options<UpdateBangumiData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateBangumi({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Test downloader connection with provided credentials
 */
export const testDownloaderConnectionMutation = (
  options?: Partial<Options<TestDownloaderConnectionData>>,
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<TestDownloaderConnectionData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<TestDownloaderConnectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await testDownloaderConnection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEpisodesQueryKey = (options: Options<GetEpisodesData>) =>
  createQueryKey("getEpisodes", options);

/**
 * Get episodes by subject ID from BGM.tv
 */
export const getEpisodesOptions = (options: Options<GetEpisodesData>) =>
  queryOptions<
    GetEpisodesResponse,
    DefaultError,
    GetEpisodesResponse,
    ReturnType<typeof getEpisodesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEpisodes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEpisodesQueryKey(options),
  });

export const getMikanRssQueryKey = (options: Options<GetMikanRssData>) =>
  createQueryKey("getMikanRss", options);

/**
 * Get bangumi detail with RSS URLs from Mikan
 */
export const getMikanRssOptions = (options: Options<GetMikanRssData>) =>
  queryOptions<
    GetMikanRssResponse,
    DefaultError,
    GetMikanRssResponse,
    ReturnType<typeof getMikanRssQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMikanRss({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMikanRssQueryKey(options),
  });

export const searchBgmtvQueryKey = (options: Options<SearchBgmtvData>) =>
  createQueryKey("searchBgmtv", options);

/**
 * Search for bangumi (Japanese anime) on BGM.tv
 */
export const searchBgmtvOptions = (options: Options<SearchBgmtvData>) =>
  queryOptions<
    SearchBgmtvResponse,
    DefaultError,
    SearchBgmtvResponse,
    ReturnType<typeof searchBgmtvQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchBgmtv({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchBgmtvQueryKey(options),
  });

export const searchMikanQueryKey = (options: Options<SearchMikanData>) =>
  createQueryKey("searchMikan", options);

/**
 * Search for bangumi on Mikan
 */
export const searchMikanOptions = (options: Options<SearchMikanData>) =>
  queryOptions<
    SearchMikanResponse,
    DefaultError,
    SearchMikanResponse,
    ReturnType<typeof searchMikanQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchMikan({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchMikanQueryKey(options),
  });

export const searchTmdbQueryKey = (options: Options<SearchTmdbData>) =>
  createQueryKey("searchTmdb", options);

/**
 * Search for anime on TMDB using discover API
 */
export const searchTmdbOptions = (options: Options<SearchTmdbData>) =>
  queryOptions<
    SearchTmdbResponse,
    DefaultError,
    SearchTmdbResponse,
    ReturnType<typeof searchTmdbQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchTmdb({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchTmdbQueryKey(options),
  });

export const getSettingsQueryKey = (options?: Options<GetSettingsData>) =>
  createQueryKey("getSettings", options);

/**
 * Get application settings
 */
export const getSettingsOptions = (options?: Options<GetSettingsData>) =>
  queryOptions<
    GetSettingsResponse,
    DefaultError,
    GetSettingsResponse,
    ReturnType<typeof getSettingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSettingsQueryKey(options),
  });

/**
 * Update application settings
 */
export const updateSettingsMutation = (
  options?: Partial<Options<UpdateSettingsData>>,
): UseMutationOptions<
  UpdateSettingsResponse,
  DefaultError,
  Options<UpdateSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSettingsResponse,
    DefaultError,
    Options<UpdateSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset settings to defaults
 */
export const resetSettingsMutation = (
  options?: Partial<Options<ResetSettingsData>>,
): UseMutationOptions<
  ResetSettingsResponse,
  DefaultError,
  Options<ResetSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    ResetSettingsResponse,
    DefaultError,
    Options<ResetSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await resetSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
