// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  cleanupLogs,
  createBangumi,
  deleteTorrents,
  getBangumi,
  getBangumiById,
  getCalendar,
  getEpisodes,
  getLogs,
  getMikanRss,
  getSettings,
  listTorrents,
  type Options,
  refreshCalendar,
  resetSettings,
  searchBgmtv,
  searchMikan,
  searchTmdb,
  searchTorrents,
  testDownloaderConnection,
  testNotification,
  testProxy,
  updateBangumi,
  updateSettings,
} from "../sdk.gen";
import type {
  CleanupLogsData,
  CleanupLogsResponse,
  CreateBangumiData,
  CreateBangumiResponse,
  DeleteTorrentsData,
  GetBangumiByIdData,
  GetBangumiByIdResponse,
  GetBangumiData,
  GetBangumiResponse,
  GetCalendarData,
  GetCalendarResponse,
  GetEpisodesData,
  GetEpisodesResponse,
  GetLogsData,
  GetLogsResponse,
  GetMikanRssData,
  GetMikanRssResponse,
  GetSettingsData,
  GetSettingsResponse,
  ListTorrentsData,
  ListTorrentsResponse,
  RefreshCalendarData,
  RefreshCalendarResponse,
  ResetSettingsData,
  ResetSettingsResponse,
  SearchBgmtvData,
  SearchBgmtvResponse,
  SearchMikanData,
  SearchMikanResponse,
  SearchTmdbData,
  SearchTmdbResponse,
  SearchTorrentsData,
  SearchTorrentsResponse,
  TestDownloaderConnectionData,
  TestNotificationData,
  TestProxyData,
  UpdateBangumiData,
  UpdateBangumiResponse,
  UpdateSettingsData,
  UpdateSettingsResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getBangumiQueryKey = (options?: Options<GetBangumiData>) =>
  createQueryKey("getBangumi", options);

/**
 * Get all bangumi
 */
export const getBangumiOptions = (options?: Options<GetBangumiData>) =>
  queryOptions<
    GetBangumiResponse,
    DefaultError,
    GetBangumiResponse,
    ReturnType<typeof getBangumiQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBangumi({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBangumiQueryKey(options),
  });

/**
 * Create a new bangumi
 */
export const createBangumiMutation = (
  options?: Partial<Options<CreateBangumiData>>,
): UseMutationOptions<
  CreateBangumiResponse,
  DefaultError,
  Options<CreateBangumiData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateBangumiResponse,
    DefaultError,
    Options<CreateBangumiData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createBangumi({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getBangumiByIdQueryKey = (options: Options<GetBangumiByIdData>) =>
  createQueryKey("getBangumiById", options);

/**
 * Get a bangumi by ID with its RSS subscriptions
 */
export const getBangumiByIdOptions = (options: Options<GetBangumiByIdData>) =>
  queryOptions<
    GetBangumiByIdResponse,
    DefaultError,
    GetBangumiByIdResponse,
    ReturnType<typeof getBangumiByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getBangumiById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getBangumiByIdQueryKey(options),
  });

/**
 * Update a bangumi
 */
export const updateBangumiMutation = (
  options?: Partial<Options<UpdateBangumiData>>,
): UseMutationOptions<
  UpdateBangumiResponse,
  DefaultError,
  Options<UpdateBangumiData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateBangumiResponse,
    DefaultError,
    Options<UpdateBangumiData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateBangumi({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getCalendarQueryKey = (options?: Options<GetCalendarData>) =>
  createQueryKey("getCalendar", options);

/**
 * Get BGM.tv calendar (weekly anime schedule)
 *
 * Returns cached data from database. If the database is empty,
 * automatically fetches from BGM.tv API and populates the database.
 */
export const getCalendarOptions = (options?: Options<GetCalendarData>) =>
  queryOptions<
    GetCalendarResponse,
    DefaultError,
    GetCalendarResponse,
    ReturnType<typeof getCalendarQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCalendar({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCalendarQueryKey(options),
  });

/**
 * Refresh BGM.tv calendar data
 *
 * Forces a refresh of the calendar data from BGM.tv API.
 * Returns the updated calendar data.
 */
export const refreshCalendarMutation = (
  options?: Partial<Options<RefreshCalendarData>>,
): UseMutationOptions<
  RefreshCalendarResponse,
  DefaultError,
  Options<RefreshCalendarData>
> => {
  const mutationOptions: UseMutationOptions<
    RefreshCalendarResponse,
    DefaultError,
    Options<RefreshCalendarData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await refreshCalendar({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Test downloader connection with provided credentials
 */
export const testDownloaderConnectionMutation = (
  options?: Partial<Options<TestDownloaderConnectionData>>,
): UseMutationOptions<
  unknown,
  DefaultError,
  Options<TestDownloaderConnectionData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<TestDownloaderConnectionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await testDownloaderConnection({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEpisodesQueryKey = (options: Options<GetEpisodesData>) =>
  createQueryKey("getEpisodes", options);

/**
 * Get episodes by subject ID from BGM.tv
 */
export const getEpisodesOptions = (options: Options<GetEpisodesData>) =>
  queryOptions<
    GetEpisodesResponse,
    DefaultError,
    GetEpisodesResponse,
    ReturnType<typeof getEpisodesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEpisodes({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEpisodesQueryKey(options),
  });

/**
 * Delete old logs (cleanup endpoint)
 */
export const cleanupLogsMutation = (
  options?: Partial<Options<CleanupLogsData>>,
): UseMutationOptions<
  CleanupLogsResponse,
  DefaultError,
  Options<CleanupLogsData>
> => {
  const mutationOptions: UseMutationOptions<
    CleanupLogsResponse,
    DefaultError,
    Options<CleanupLogsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await cleanupLogs({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getLogsQueryKey = (options?: Options<GetLogsData>) =>
  createQueryKey("getLogs", options);

/**
 * Get logs with optional filtering and pagination
 */
export const getLogsOptions = (options?: Options<GetLogsData>) =>
  queryOptions<
    GetLogsResponse,
    DefaultError,
    GetLogsResponse,
    ReturnType<typeof getLogsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLogs({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLogsQueryKey(options),
  });

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getLogsInfiniteQueryKey = (
  options?: Options<GetLogsData>,
): QueryKey<Options<GetLogsData>> => createQueryKey("getLogs", options, true);

/**
 * Get logs with optional filtering and pagination
 */
export const getLogsInfiniteOptions = (options?: Options<GetLogsData>) =>
  infiniteQueryOptions<
    GetLogsResponse,
    DefaultError,
    InfiniteData<GetLogsResponse>,
    QueryKey<Options<GetLogsData>>,
    | number
    | null
    | Pick<
        QueryKey<Options<GetLogsData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetLogsData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getLogs({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getLogsInfiniteQueryKey(options),
    },
  );

export const getMikanRssQueryKey = (options: Options<GetMikanRssData>) =>
  createQueryKey("getMikanRss", options);

/**
 * Get bangumi detail with RSS URLs from Mikan
 */
export const getMikanRssOptions = (options: Options<GetMikanRssData>) =>
  queryOptions<
    GetMikanRssResponse,
    DefaultError,
    GetMikanRssResponse,
    ReturnType<typeof getMikanRssQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMikanRss({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMikanRssQueryKey(options),
  });

/**
 * Test Telegram notification by sending a test message
 */
export const testNotificationMutation = (
  options?: Partial<Options<TestNotificationData>>,
): UseMutationOptions<unknown, DefaultError, Options<TestNotificationData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<TestNotificationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await testNotification({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Test proxy connection by making a request to mikanani.me
 */
export const testProxyMutation = (
  options?: Partial<Options<TestProxyData>>,
): UseMutationOptions<unknown, DefaultError, Options<TestProxyData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<TestProxyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await testProxy({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const searchBgmtvQueryKey = (options: Options<SearchBgmtvData>) =>
  createQueryKey("searchBgmtv", options);

/**
 * Search for bangumi (Japanese anime) on BGM.tv
 */
export const searchBgmtvOptions = (options: Options<SearchBgmtvData>) =>
  queryOptions<
    SearchBgmtvResponse,
    DefaultError,
    SearchBgmtvResponse,
    ReturnType<typeof searchBgmtvQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchBgmtv({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchBgmtvQueryKey(options),
  });

export const searchMikanQueryKey = (options: Options<SearchMikanData>) =>
  createQueryKey("searchMikan", options);

/**
 * Search for bangumi on Mikan
 */
export const searchMikanOptions = (options: Options<SearchMikanData>) =>
  queryOptions<
    SearchMikanResponse,
    DefaultError,
    SearchMikanResponse,
    ReturnType<typeof searchMikanQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchMikan({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchMikanQueryKey(options),
  });

export const searchTmdbQueryKey = (options: Options<SearchTmdbData>) =>
  createQueryKey("searchTmdb", options);

/**
 * Search for anime on TMDB using discover API
 */
export const searchTmdbOptions = (options: Options<SearchTmdbData>) =>
  queryOptions<
    SearchTmdbResponse,
    DefaultError,
    SearchTmdbResponse,
    ReturnType<typeof searchTmdbQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchTmdb({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchTmdbQueryKey(options),
  });

export const getSettingsQueryKey = (options?: Options<GetSettingsData>) =>
  createQueryKey("getSettings", options);

/**
 * Get application settings
 */
export const getSettingsOptions = (options?: Options<GetSettingsData>) =>
  queryOptions<
    GetSettingsResponse,
    DefaultError,
    GetSettingsResponse,
    ReturnType<typeof getSettingsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSettings({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSettingsQueryKey(options),
  });

/**
 * Update application settings
 */
export const updateSettingsMutation = (
  options?: Partial<Options<UpdateSettingsData>>,
): UseMutationOptions<
  UpdateSettingsResponse,
  DefaultError,
  Options<UpdateSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateSettingsResponse,
    DefaultError,
    Options<UpdateSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset settings to defaults
 */
export const resetSettingsMutation = (
  options?: Partial<Options<ResetSettingsData>>,
): UseMutationOptions<
  ResetSettingsResponse,
  DefaultError,
  Options<ResetSettingsData>
> => {
  const mutationOptions: UseMutationOptions<
    ResetSettingsResponse,
    DefaultError,
    Options<ResetSettingsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await resetSettings({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listTorrentsQueryKey = (options?: Options<ListTorrentsData>) =>
  createQueryKey("listTorrents", options);

/**
 * List all torrents
 */
export const listTorrentsOptions = (options?: Options<ListTorrentsData>) =>
  queryOptions<
    ListTorrentsResponse,
    DefaultError,
    ListTorrentsResponse,
    ReturnType<typeof listTorrentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTorrents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listTorrentsQueryKey(options),
  });

/**
 * Delete torrents
 */
export const deleteTorrentsMutation = (
  options?: Partial<Options<DeleteTorrentsData>>,
): UseMutationOptions<unknown, DefaultError, Options<DeleteTorrentsData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DefaultError,
    Options<DeleteTorrentsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteTorrents({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const searchTorrentsQueryKey = (options: Options<SearchTorrentsData>) =>
  createQueryKey("searchTorrents", options);

/**
 * Search for torrents from a specific source (Nyaa or Mikan)
 */
export const searchTorrentsOptions = (options: Options<SearchTorrentsData>) =>
  queryOptions<
    SearchTorrentsResponse,
    DefaultError,
    SearchTorrentsResponse,
    ReturnType<typeof searchTorrentsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await searchTorrents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: searchTorrentsQueryKey(options),
  });
