// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiTrackingByIdData, DeleteApiTrackingByIdErrors, DeleteApiTrackingByIdResponses, GetApiBangumiSearchTmdbData, GetApiBangumiSearchTmdbErrors, GetApiBangumiSearchTmdbResponses, GetApiCalendarData, GetApiCalendarErrors, GetApiCalendarResponses, GetApiHealthData, GetApiHealthResponses, GetApiRssSearchData, GetApiRssSearchErrors, GetApiRssSearchResponses, GetApiSettingsData, GetApiSettingsResponses, GetApiTrackingBangumisData, GetApiTrackingBangumisResponses, GetApiTrackingByIdData, GetApiTrackingByIdErrors, GetApiTrackingByIdResponses, GetApiTrackingData, GetApiTrackingResponses, PostApiDownloaderTestData, PostApiDownloaderTestErrors, PostApiDownloaderTestResponses, PostApiMediaImportData, PostApiMediaImportErrors, PostApiMediaImportResponses, PostApiMediaLibrariesData, PostApiMediaLibrariesErrors, PostApiMediaLibrariesResponses, PostApiMediaTestData, PostApiMediaTestErrors, PostApiMediaTestResponses, PostApiNotificationTestData, PostApiNotificationTestErrors, PostApiNotificationTestResponses, PostApiRssDownloadData, PostApiRssDownloadErrors, PostApiRssDownloadResponses, PostApiTrackingData, PostApiTrackingErrors, PostApiTrackingResponses, PutApiBangumiByIdTmdbIdData, PutApiBangumiByIdTmdbIdErrors, PutApiBangumiByIdTmdbIdResponses, PutApiSettingsData, PutApiSettingsErrors, PutApiSettingsResponses, PutApiTrackingByIdData, PutApiTrackingByIdErrors, PutApiTrackingByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiHealth = <ThrowOnError extends boolean = false>(options?: Options<GetApiHealthData, ThrowOnError>) => (options?.client ?? client).get<GetApiHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

export const getApiCalendar = <ThrowOnError extends boolean = false>(options: Options<GetApiCalendarData, ThrowOnError>) => (options.client ?? client).get<GetApiCalendarResponses, GetApiCalendarErrors, ThrowOnError>({ url: '/api/calendar', ...options });

export const getApiSettings = <ThrowOnError extends boolean = false>(options?: Options<GetApiSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetApiSettingsResponses, unknown, ThrowOnError>({ url: '/api/settings', ...options });

export const putApiSettings = <ThrowOnError extends boolean = false>(options?: Options<PutApiSettingsData, ThrowOnError>) => (options?.client ?? client).put<PutApiSettingsResponses, PutApiSettingsErrors, ThrowOnError>({
    url: '/api/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const getApiTracking = <ThrowOnError extends boolean = false>(options?: Options<GetApiTrackingData, ThrowOnError>) => (options?.client ?? client).get<GetApiTrackingResponses, unknown, ThrowOnError>({ url: '/api/tracking', ...options });

export const postApiTracking = <ThrowOnError extends boolean = false>(options?: Options<PostApiTrackingData, ThrowOnError>) => (options?.client ?? client).post<PostApiTrackingResponses, PostApiTrackingErrors, ThrowOnError>({
    url: '/api/tracking',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const getApiTrackingBangumis = <ThrowOnError extends boolean = false>(options?: Options<GetApiTrackingBangumisData, ThrowOnError>) => (options?.client ?? client).get<GetApiTrackingBangumisResponses, unknown, ThrowOnError>({ url: '/api/tracking/bangumis', ...options });

export const deleteApiTrackingById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiTrackingByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiTrackingByIdResponses, DeleteApiTrackingByIdErrors, ThrowOnError>({ url: '/api/tracking/{id}', ...options });

export const getApiTrackingById = <ThrowOnError extends boolean = false>(options: Options<GetApiTrackingByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiTrackingByIdResponses, GetApiTrackingByIdErrors, ThrowOnError>({ url: '/api/tracking/{id}', ...options });

export const putApiTrackingById = <ThrowOnError extends boolean = false>(options: Options<PutApiTrackingByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiTrackingByIdResponses, PutApiTrackingByIdErrors, ThrowOnError>({
    url: '/api/tracking/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options.headers
    }
});

export const getApiRssSearch = <ThrowOnError extends boolean = false>(options: Options<GetApiRssSearchData, ThrowOnError>) => (options.client ?? client).get<GetApiRssSearchResponses, GetApiRssSearchErrors, ThrowOnError>({ url: '/api/rss/search', ...options });

export const postApiRssDownload = <ThrowOnError extends boolean = false>(options?: Options<PostApiRssDownloadData, ThrowOnError>) => (options?.client ?? client).post<PostApiRssDownloadResponses, PostApiRssDownloadErrors, ThrowOnError>({
    url: '/api/rss/download',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const postApiDownloaderTest = <ThrowOnError extends boolean = false>(options?: Options<PostApiDownloaderTestData, ThrowOnError>) => (options?.client ?? client).post<PostApiDownloaderTestResponses, PostApiDownloaderTestErrors, ThrowOnError>({
    url: '/api/downloader/test',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const postApiNotificationTest = <ThrowOnError extends boolean = false>(options?: Options<PostApiNotificationTestData, ThrowOnError>) => (options?.client ?? client).post<PostApiNotificationTestResponses, PostApiNotificationTestErrors, ThrowOnError>({
    url: '/api/notification/test',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const postApiMediaTest = <ThrowOnError extends boolean = false>(options?: Options<PostApiMediaTestData, ThrowOnError>) => (options?.client ?? client).post<PostApiMediaTestResponses, PostApiMediaTestErrors, ThrowOnError>({
    url: '/api/media/test',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const postApiMediaLibraries = <ThrowOnError extends boolean = false>(options?: Options<PostApiMediaLibrariesData, ThrowOnError>) => (options?.client ?? client).post<PostApiMediaLibrariesResponses, PostApiMediaLibrariesErrors, ThrowOnError>({
    url: '/api/media/libraries',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const postApiMediaImport = <ThrowOnError extends boolean = false>(options?: Options<PostApiMediaImportData, ThrowOnError>) => (options?.client ?? client).post<PostApiMediaImportResponses, PostApiMediaImportErrors, ThrowOnError>({
    url: '/api/media/import',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const getApiBangumiSearchTmdb = <ThrowOnError extends boolean = false>(options: Options<GetApiBangumiSearchTmdbData, ThrowOnError>) => (options.client ?? client).get<GetApiBangumiSearchTmdbResponses, GetApiBangumiSearchTmdbErrors, ThrowOnError>({ url: '/api/bangumi/search-tmdb', ...options });

export const putApiBangumiByIdTmdbId = <ThrowOnError extends boolean = false>(options: Options<PutApiBangumiByIdTmdbIdData, ThrowOnError>) => (options.client ?? client).put<PutApiBangumiByIdTmdbIdResponses, PutApiBangumiByIdTmdbIdErrors, ThrowOnError>({
    url: '/api/bangumi/{id}/tmdb-id',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options.headers
    }
});
