// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiBangumiSeasonData, GetApiBangumiSeasonErrors, GetApiBangumiSeasonResponses, GetApiCalendarData, GetApiCalendarErrors, GetApiCalendarResponses, GetApiHealthData, GetApiHealthResponses, GetApiSettingsData, GetApiSettingsResponses, PutApiSettingsData, PutApiSettingsErrors, PutApiSettingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiHealth = <ThrowOnError extends boolean = false>(options?: Options<GetApiHealthData, ThrowOnError>) => (options?.client ?? client).get<GetApiHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

export const getApiBangumiSeason = <ThrowOnError extends boolean = false>(options: Options<GetApiBangumiSeasonData, ThrowOnError>) => (options.client ?? client).get<GetApiBangumiSeasonResponses, GetApiBangumiSeasonErrors, ThrowOnError>({ url: '/api/bangumi/season', ...options });

export const getApiCalendar = <ThrowOnError extends boolean = false>(options: Options<GetApiCalendarData, ThrowOnError>) => (options.client ?? client).get<GetApiCalendarResponses, GetApiCalendarErrors, ThrowOnError>({ url: '/api/calendar', ...options });

export const getApiSettings = <ThrowOnError extends boolean = false>(options?: Options<GetApiSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetApiSettingsResponses, unknown, ThrowOnError>({ url: '/api/settings', ...options });

export const putApiSettings = <ThrowOnError extends boolean = false>(options?: Options<PutApiSettingsData, ThrowOnError>) => (options?.client ?? client).put<PutApiSettingsResponses, PutApiSettingsErrors, ThrowOnError>({
    url: '/api/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});
