// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiTrackingByIdData, DeleteApiTrackingByIdErrors, DeleteApiTrackingByIdResponses, GetApiBangumiSeasonData, GetApiBangumiSeasonErrors, GetApiBangumiSeasonResponses, GetApiCalendarData, GetApiCalendarErrors, GetApiCalendarResponses, GetApiHealthData, GetApiHealthResponses, GetApiSettingsData, GetApiSettingsResponses, GetApiTrackingBangumisData, GetApiTrackingBangumisResponses, GetApiTrackingByIdData, GetApiTrackingByIdErrors, GetApiTrackingByIdResponses, GetApiTrackingData, GetApiTrackingResponses, PostApiTrackingData, PostApiTrackingErrors, PostApiTrackingResponses, PutApiSettingsData, PutApiSettingsErrors, PutApiSettingsResponses, PutApiTrackingByIdData, PutApiTrackingByIdErrors, PutApiTrackingByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiHealth = <ThrowOnError extends boolean = false>(options?: Options<GetApiHealthData, ThrowOnError>) => (options?.client ?? client).get<GetApiHealthResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

export const getApiBangumiSeason = <ThrowOnError extends boolean = false>(options: Options<GetApiBangumiSeasonData, ThrowOnError>) => (options.client ?? client).get<GetApiBangumiSeasonResponses, GetApiBangumiSeasonErrors, ThrowOnError>({ url: '/api/bangumi/season', ...options });

export const getApiCalendar = <ThrowOnError extends boolean = false>(options: Options<GetApiCalendarData, ThrowOnError>) => (options.client ?? client).get<GetApiCalendarResponses, GetApiCalendarErrors, ThrowOnError>({ url: '/api/calendar', ...options });

export const getApiSettings = <ThrowOnError extends boolean = false>(options?: Options<GetApiSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetApiSettingsResponses, unknown, ThrowOnError>({ url: '/api/settings', ...options });

export const putApiSettings = <ThrowOnError extends boolean = false>(options?: Options<PutApiSettingsData, ThrowOnError>) => (options?.client ?? client).put<PutApiSettingsResponses, PutApiSettingsErrors, ThrowOnError>({
    url: '/api/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const getApiTracking = <ThrowOnError extends boolean = false>(options?: Options<GetApiTrackingData, ThrowOnError>) => (options?.client ?? client).get<GetApiTrackingResponses, unknown, ThrowOnError>({ url: '/api/tracking', ...options });

export const postApiTracking = <ThrowOnError extends boolean = false>(options?: Options<PostApiTrackingData, ThrowOnError>) => (options?.client ?? client).post<PostApiTrackingResponses, PostApiTrackingErrors, ThrowOnError>({
    url: '/api/tracking',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options?.headers
    }
});

export const getApiTrackingBangumis = <ThrowOnError extends boolean = false>(options?: Options<GetApiTrackingBangumisData, ThrowOnError>) => (options?.client ?? client).get<GetApiTrackingBangumisResponses, unknown, ThrowOnError>({ url: '/api/tracking/bangumis', ...options });

export const deleteApiTrackingById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiTrackingByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiTrackingByIdResponses, DeleteApiTrackingByIdErrors, ThrowOnError>({ url: '/api/tracking/{id}', ...options });

export const getApiTrackingById = <ThrowOnError extends boolean = false>(options: Options<GetApiTrackingByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiTrackingByIdResponses, GetApiTrackingByIdErrors, ThrowOnError>({ url: '/api/tracking/{id}', ...options });

export const putApiTrackingById = <ThrowOnError extends boolean = false>(options: Options<PutApiTrackingByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiTrackingByIdResponses, PutApiTrackingByIdErrors, ThrowOnError>({
    url: '/api/tracking/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json;charset=utf-8',
        ...options.headers
    }
});
