// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type AboutResponse = {
    arch: string;
    autoUpdate: boolean;
    changelog: string;
    latest: string;
    needUpdate: boolean;
    platform: string;
    publishedAt?: UtcTime;
    version: string;
};

export type UtcTime = string;

export type UpdateResponse = {
    message: string;
    success: boolean;
};

export type CalendarEntry = {
    bangumis: Array<BangumiResponse>;
    weekday: number;
};

export type BangumiResponse = {
    airDate: Day;
    bgmtvId?: number;
    createdAt: UtcTime;
    id: number;
    kind: BangumiKind;
    mikanId?: number;
    posterUrl?: string;
    season?: number;
    titleChs: string;
    titleJap?: string;
    tmdbId?: number;
    totalEpisodes?: number;
};

export type Day = string;

export type BangumiKind = 'tv' | 'web' | 'movie' | 'ova';

export type UserPreference = {
    downloader: DownloaderConfig;
    filter: FilterConfig;
    notification: NotificationConfig;
    tmdb: TmdbConfig;
    washing: WashingConfig;
};

export type DownloaderConfig = {
    password: string;
    savePath: string;
    url: string;
    username: string;
};

export type FilterConfig = {
    globalRssFilter: Array<string>;
};

export type WashingConfig = {
    groupPriority: Array<Group>;
    subtitlePriority: Array<Array<Subtitle>>;
};

export type Group = {
    aliases: Array<string>;
    name: string;
};

export type Subtitle = 'CHS' | 'CHT' | 'JPN' | 'ENG';

export type NotificationConfig = {
    botToken: string;
    chatId: string;
};

export type TmdbConfig = {
    apiKey: string;
    language: string;
};

export type TrackingResponse = {
    autoComplete: boolean;
    bangumiId: number;
    createdAt: UtcTime;
    currentEpisode: number;
    episodeOffset: number;
    id: number;
    isBDrip: boolean;
    lastPubdate?: UtcTime;
    rssEnabled: boolean;
    rssUrl?: string;
    trackingType: TrackingType;
};

export type TrackingType = 'subscription' | 'collection';

export type TrackingWithBangumiResponse = {
    bangumi: BangumiResponse;
    tracking: TrackingResponse;
};

export type CreateTrackingRequest = {
    bangumiId: number;
    currentEpisode?: number;
    episodeOffset?: number;
    mikanId?: number;
    rssUrl?: string;
    trackingType: TrackingType;
};

export type UpdateTrackingRequest = {
    autoComplete?: boolean;
    currentEpisode?: number;
    episodeOffset?: number;
    rssEnabled?: boolean;
    rssUrl?: string;
    trackingType?: TrackingType;
};

export type RssSearchResult = {
    infoHash?: string;
    pubDate?: UtcTime;
    source: string;
    title: string;
    torrentUrl?: string;
};

export type DownloadTorrentRequest = {
    torrentUrl: string;
};

export type TestDownloaderResponse = {
    message: string;
    success: boolean;
    version?: string;
};

export type TestDownloaderRequest = {
    password: string;
    url: string;
    username: string;
};

export type TestNotificationResponse = {
    message: string;
    success: boolean;
};

export type TestNotificationRequest = {
    botToken: string;
    chatId: string;
};

export type TmdbSearchResult = {
    mediaType: string;
    posterUrl?: string;
    title: string;
    tmdbId: number;
    year?: number;
};

export type MikanSearchResultDto = {
    mikanId: number;
    season?: number;
    title: string;
};

export type UpdateBangumiTmdbIdRequest = {
    tmdbId?: number;
};

export type LogsResponse = {
    entries: Array<LogEntry>;
    page: number;
    pageSize: number;
    total: number;
};

export type LogEntry = {
    component: string;
    level: string;
    message: string;
    time: UtcTime;
};

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetApiHealthResponses = {
    200: string;
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];

export type GetApiAboutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/about';
};

export type GetApiAboutResponses = {
    200: AboutResponse;
};

export type GetApiAboutResponse = GetApiAboutResponses[keyof GetApiAboutResponses];

export type PostApiUpdateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/update';
};

export type PostApiUpdateResponses = {
    200: UpdateResponse;
};

export type PostApiUpdateResponse = PostApiUpdateResponses[keyof PostApiUpdateResponses];

export type GetApiCalendarData = {
    body?: never;
    path?: never;
    query: {
        year: number;
        season: 'Winter' | 'Spring' | 'Summer' | 'Fall';
    };
    url: '/api/calendar';
};

export type GetApiCalendarErrors = {
    /**
     * Invalid `season` or `year`
     */
    400: unknown;
};

export type GetApiCalendarResponses = {
    200: Array<CalendarEntry>;
};

export type GetApiCalendarResponse = GetApiCalendarResponses[keyof GetApiCalendarResponses];

export type GetApiSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type GetApiSettingsResponses = {
    200: UserPreference;
};

export type GetApiSettingsResponse = GetApiSettingsResponses[keyof GetApiSettingsResponses];

export type PutApiSettingsData = {
    body?: UserPreference;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type PutApiSettingsErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
};

export type PutApiSettingsResponses = {
    200: UserPreference;
};

export type PutApiSettingsResponse = PutApiSettingsResponses[keyof PutApiSettingsResponses];

export type GetApiTrackingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tracking';
};

export type GetApiTrackingResponses = {
    200: Array<TrackingResponse>;
};

export type GetApiTrackingResponse = GetApiTrackingResponses[keyof GetApiTrackingResponses];

export type PostApiTrackingData = {
    body?: CreateTrackingRequest;
    path?: never;
    query?: never;
    url: '/api/tracking';
};

export type PostApiTrackingErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
};

export type PostApiTrackingResponses = {
    200: TrackingResponse;
};

export type PostApiTrackingResponse = PostApiTrackingResponses[keyof PostApiTrackingResponses];

export type GetApiTrackingBangumisData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tracking/bangumis';
};

export type GetApiTrackingBangumisResponses = {
    200: Array<TrackingWithBangumiResponse>;
};

export type GetApiTrackingBangumisResponse = GetApiTrackingBangumisResponses[keyof GetApiTrackingBangumisResponses];

export type DeleteApiTrackingByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tracking/{id}';
};

export type DeleteApiTrackingByIdErrors = {
    /**
     * `id` not found
     */
    404: unknown;
};

export type DeleteApiTrackingByIdResponses = {
    200: unknown;
};

export type GetApiTrackingByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tracking/{id}';
};

export type GetApiTrackingByIdErrors = {
    /**
     * `id` not found
     */
    404: unknown;
};

export type GetApiTrackingByIdResponses = {
    200: TrackingResponse;
};

export type GetApiTrackingByIdResponse = GetApiTrackingByIdResponses[keyof GetApiTrackingByIdResponses];

export type PutApiTrackingByIdData = {
    body?: UpdateTrackingRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tracking/{id}';
};

export type PutApiTrackingByIdErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
    /**
     * `id` not found
     */
    404: unknown;
};

export type PutApiTrackingByIdResponses = {
    200: TrackingResponse;
};

export type PutApiTrackingByIdResponse = PutApiTrackingByIdResponses[keyof PutApiTrackingByIdResponses];

export type GetApiRssSearchData = {
    body?: never;
    path?: never;
    query: {
        keyword: string;
    };
    url: '/api/rss/search';
};

export type GetApiRssSearchErrors = {
    /**
     * Invalid `keyword`
     */
    400: unknown;
};

export type GetApiRssSearchResponses = {
    200: Array<RssSearchResult>;
};

export type GetApiRssSearchResponse = GetApiRssSearchResponses[keyof GetApiRssSearchResponses];

export type PostApiRssDownloadData = {
    body?: DownloadTorrentRequest;
    path?: never;
    query?: never;
    url: '/api/rss/download';
};

export type PostApiRssDownloadErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
};

export type PostApiRssDownloadResponses = {
    200: unknown;
};

export type PostApiDownloaderTestData = {
    body?: TestDownloaderRequest;
    path?: never;
    query?: never;
    url: '/api/downloader/test';
};

export type PostApiDownloaderTestErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
};

export type PostApiDownloaderTestResponses = {
    200: TestDownloaderResponse;
};

export type PostApiDownloaderTestResponse = PostApiDownloaderTestResponses[keyof PostApiDownloaderTestResponses];

export type PostApiNotificationTestData = {
    body?: TestNotificationRequest;
    path?: never;
    query?: never;
    url: '/api/notification/test';
};

export type PostApiNotificationTestErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
};

export type PostApiNotificationTestResponses = {
    200: TestNotificationResponse;
};

export type PostApiNotificationTestResponse = PostApiNotificationTestResponses[keyof PostApiNotificationTestResponses];

export type GetApiBangumiSearchTmdbData = {
    body?: never;
    path?: never;
    query: {
        keyword: string;
        year?: number;
    };
    url: '/api/bangumi/search-tmdb';
};

export type GetApiBangumiSearchTmdbErrors = {
    /**
     * Invalid `year` or `keyword`
     */
    400: unknown;
};

export type GetApiBangumiSearchTmdbResponses = {
    200: Array<TmdbSearchResult>;
};

export type GetApiBangumiSearchTmdbResponse = GetApiBangumiSearchTmdbResponses[keyof GetApiBangumiSearchTmdbResponses];

export type GetApiBangumiSearchMikanData = {
    body?: never;
    path?: never;
    query: {
        keyword: string;
    };
    url: '/api/bangumi/search-mikan';
};

export type GetApiBangumiSearchMikanErrors = {
    /**
     * Invalid `keyword`
     */
    400: unknown;
};

export type GetApiBangumiSearchMikanResponses = {
    200: Array<MikanSearchResultDto>;
};

export type GetApiBangumiSearchMikanResponse = GetApiBangumiSearchMikanResponses[keyof GetApiBangumiSearchMikanResponses];

export type PutApiBangumiByIdTmdbIdData = {
    body?: UpdateBangumiTmdbIdRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/bangumi/{id}/tmdb-id';
};

export type PutApiBangumiByIdTmdbIdErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
    /**
     * `id` not found
     */
    404: unknown;
};

export type PutApiBangumiByIdTmdbIdResponses = {
    200: unknown;
};

export type GetApiBangumiByIdEpisodeOffsetData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/bangumi/{id}/episode-offset';
};

export type GetApiBangumiByIdEpisodeOffsetErrors = {
    /**
     * `id` not found
     */
    404: unknown;
};

export type GetApiBangumiByIdEpisodeOffsetResponses = {
    200: number;
};

export type GetApiBangumiByIdEpisodeOffsetResponse = GetApiBangumiByIdEpisodeOffsetResponses[keyof GetApiBangumiByIdEpisodeOffsetResponses];

export type GetApiLogsData = {
    body?: never;
    path?: never;
    query: {
        date: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/logs';
};

export type GetApiLogsErrors = {
    /**
     * Invalid `pageSize` or `page` or `date`
     */
    400: unknown;
};

export type GetApiLogsResponses = {
    200: LogsResponse;
};

export type GetApiLogsResponse = GetApiLogsResponses[keyof GetApiLogsResponses];
