// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type BangumiResponse = {
    airDate?: Day;
    bgmtvId?: number;
    id?: number;
    kind: BangumiKind;
    mikanId?: number;
    posterUrl?: string;
    season?: number;
    titleChs: string;
    titleJap?: string;
    tmdbId?: number;
};

export type Day = string;

export type BangumiKind = 'tv' | 'web' | 'movie' | 'ova';

export type CalendarEntry = {
    bangumis: Array<BangumiResponse>;
    weekday: number;
};

export type SettingResponse = {
    downloader?: DownloaderConfigResponse;
    filter?: FilterConfigResponse;
    notification?: NotificationConfigResponse;
    tmdb?: TmdbConfigResponse;
};

export type DownloaderConfigResponse = {
    savePath: string;
    url: string;
    username: string;
};

export type FilterConfigResponse = {
    globalRssFilter: Array<string>;
};

export type NotificationConfigResponse = {
    chatId: string;
};

export type TmdbConfigResponse = {
    apiKeyConfigured: boolean;
};

export type UserPreference = {
    downloader?: DownloaderConfig;
    filter?: FilterConfig;
    notification?: NotificationConfig;
    tmdb?: TmdbConfig;
};

export type DownloaderConfig = {
    password: string;
    savePath: string;
    url: string;
    username: string;
};

export type FilterConfig = {
    globalRssFilter: Array<string>;
};

export type NotificationConfig = {
    botToken: string;
    chatId: string;
};

export type TmdbConfig = {
    apiKey: string;
    language?: string;
};

export type TrackingResponse = {
    bangumiId: number;
    createdAt?: UtcTime;
    currentEpisode: number;
    id: number;
    lastPubdate?: UtcTime;
    rssUrl?: string;
    trackingType: TrackingType;
};

export type TrackingType = 'Subscription' | 'Collection';

export type UtcTime = string;

export type TrackingWithBangumiResponse = {
    bangumi: BangumiResponse;
    tracking: TrackingResponse;
};

export type CreateTrackingRequest = {
    bangumiId: number;
    currentEpisode?: number;
    mikanId?: number;
    trackingType: TrackingType;
};

export type UpdateTrackingRequest = {
    currentEpisode?: number;
    rssUrl?: string;
    trackingType?: TrackingType;
};

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetApiHealthResponses = {
    200: string;
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];

export type GetApiBangumiSeasonData = {
    body?: never;
    path?: never;
    query: {
        year: number;
        season: 'Winter' | 'Spring' | 'Summer' | 'Fall';
        force?: boolean;
    };
    url: '/api/bangumi/season';
};

export type GetApiBangumiSeasonErrors = {
    /**
     * Invalid `force` or `season` or `year`
     */
    400: unknown;
};

export type GetApiBangumiSeasonResponses = {
    200: Array<BangumiResponse>;
};

export type GetApiBangumiSeasonResponse = GetApiBangumiSeasonResponses[keyof GetApiBangumiSeasonResponses];

export type GetApiCalendarData = {
    body?: never;
    path?: never;
    query: {
        year: number;
        season: 'Winter' | 'Spring' | 'Summer' | 'Fall';
    };
    url: '/api/calendar';
};

export type GetApiCalendarErrors = {
    /**
     * Invalid `season` or `year`
     */
    400: unknown;
};

export type GetApiCalendarResponses = {
    200: Array<CalendarEntry>;
};

export type GetApiCalendarResponse = GetApiCalendarResponses[keyof GetApiCalendarResponses];

export type GetApiSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type GetApiSettingsResponses = {
    200: SettingResponse;
};

export type GetApiSettingsResponse = GetApiSettingsResponses[keyof GetApiSettingsResponses];

export type PutApiSettingsData = {
    body?: UserPreference;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type PutApiSettingsErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
};

export type PutApiSettingsResponses = {
    200: SettingResponse;
};

export type PutApiSettingsResponse = PutApiSettingsResponses[keyof PutApiSettingsResponses];

export type GetApiTrackingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tracking';
};

export type GetApiTrackingResponses = {
    200: Array<TrackingResponse>;
};

export type GetApiTrackingResponse = GetApiTrackingResponses[keyof GetApiTrackingResponses];

export type PostApiTrackingData = {
    body?: CreateTrackingRequest;
    path?: never;
    query?: never;
    url: '/api/tracking';
};

export type PostApiTrackingErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
};

export type PostApiTrackingResponses = {
    200: TrackingResponse;
};

export type PostApiTrackingResponse = PostApiTrackingResponses[keyof PostApiTrackingResponses];

export type GetApiTrackingBangumisData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tracking/bangumis';
};

export type GetApiTrackingBangumisResponses = {
    200: Array<TrackingWithBangumiResponse>;
};

export type GetApiTrackingBangumisResponse = GetApiTrackingBangumisResponses[keyof GetApiTrackingBangumisResponses];

export type DeleteApiTrackingByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tracking/{id}';
};

export type DeleteApiTrackingByIdErrors = {
    /**
     * `id` not found
     */
    404: unknown;
};

export type DeleteApiTrackingByIdResponses = {
    200: unknown;
};

export type GetApiTrackingByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tracking/{id}';
};

export type GetApiTrackingByIdErrors = {
    /**
     * `id` not found
     */
    404: unknown;
};

export type GetApiTrackingByIdResponses = {
    200: TrackingResponse;
};

export type GetApiTrackingByIdResponse = GetApiTrackingByIdResponses[keyof GetApiTrackingByIdResponses];

export type PutApiTrackingByIdData = {
    body?: UpdateTrackingRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tracking/{id}';
};

export type PutApiTrackingByIdErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
    /**
     * `id` not found
     */
    404: unknown;
};

export type PutApiTrackingByIdResponses = {
    200: TrackingResponse;
};

export type PutApiTrackingByIdResponse = PutApiTrackingByIdResponses[keyof PutApiTrackingByIdResponses];
