// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type BangumiResponse = {
    airDate?: Day;
    bangumiSeason?: string;
    id?: number;
    kind: string;
    posterUrl?: string;
    seasonNumber?: number;
    titleChs: string;
    titleJap?: string;
};

export type Day = string;

export type CalendarEntry = {
    bangumis: Array<BangumiResponse>;
    weekday: number;
};

export type SettingResponse = {
    downloader?: DownloaderConfigResponse;
    filter?: FilterConfigResponse;
    notification?: NotificationConfigResponse;
    tmdb?: TmdbConfigResponse;
};

export type DownloaderConfigResponse = {
    savePath: string;
    url: string;
    username: string;
};

export type FilterConfigResponse = {
    globalRssFilter: Array<string>;
};

export type NotificationConfigResponse = {
    chatId: string;
};

export type TmdbConfigResponse = {
    apiKeyConfigured: boolean;
};

export type UserPreference = {
    downloader?: DownloaderConfig;
    filter?: FilterConfig;
    notification?: NotificationConfig;
    tmdb?: TmdbConfig;
};

export type DownloaderConfig = {
    password: string;
    savePath: string;
    url: string;
    username: string;
};

export type FilterConfig = {
    globalRssFilter: Array<string>;
};

export type NotificationConfig = {
    botToken: string;
    chatId: string;
};

export type TmdbConfig = {
    apiKey: string;
    language?: string;
};

export type GetApiHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type GetApiHealthResponses = {
    200: string;
};

export type GetApiHealthResponse = GetApiHealthResponses[keyof GetApiHealthResponses];

export type GetApiBangumiSeasonData = {
    body?: never;
    path?: never;
    query: {
        year: number;
        season: string;
        force?: boolean;
    };
    url: '/api/bangumi/season';
};

export type GetApiBangumiSeasonErrors = {
    /**
     * Invalid `force` or `season` or `year`
     */
    400: unknown;
};

export type GetApiBangumiSeasonResponses = {
    200: Array<BangumiResponse>;
};

export type GetApiBangumiSeasonResponse = GetApiBangumiSeasonResponses[keyof GetApiBangumiSeasonResponses];

export type GetApiCalendarData = {
    body?: never;
    path?: never;
    query: {
        year: number;
        season: string;
    };
    url: '/api/calendar';
};

export type GetApiCalendarErrors = {
    /**
     * Invalid `season` or `year`
     */
    400: unknown;
};

export type GetApiCalendarResponses = {
    200: Array<CalendarEntry>;
};

export type GetApiCalendarResponse = GetApiCalendarResponses[keyof GetApiCalendarResponses];

export type GetApiSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type GetApiSettingsResponses = {
    200: SettingResponse;
};

export type GetApiSettingsResponse = GetApiSettingsResponses[keyof GetApiSettingsResponses];

export type PutApiSettingsData = {
    body?: UserPreference;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type PutApiSettingsErrors = {
    /**
     * Invalid `body`
     */
    400: unknown;
};

export type PutApiSettingsResponses = {
    200: SettingResponse;
};

export type PutApiSettingsResponse = PutApiSettingsResponses[keyof PutApiSettingsResponses];
